module.exports = [
  {id:"asia",en:"Asia",zh:"亚洲",cat:"geography",emoji:"🌏"},
  {id:"europe",en:"Europe",zh:"欧洲",cat:"geography",emoji:"🌍"},
  {id:"africa",en:"Africa",zh:"非洲",cat:"geography",emoji:"🌍"},
  {id:"north_america",en:"North America",zh:"北美洲",cat:"geography",emoji:"🌎"},
  {id:"south_america",en:"South America",zh:"南美洲",cat:"geography",emoji:"🌎"},
  {id:"australia_cont",en:"Australia",zh:"澳大利亚",cat:"geography",emoji:"🦘"},
  {id:"antarctica",en:"Antarctica",zh:"南极洲",cat:"geography",emoji:"🧊"},
  {id:"pacific_ocean",en:"Pacific Ocean",zh:"太平洋",cat:"geography",emoji:"🌊"},
  {id:"atlantic_ocean",en:"Atlantic Ocean",zh:"大西洋",cat:"geography",emoji:"🌊"},
  {id:"indian_ocean",en:"Indian Ocean",zh:"印度洋",cat:"geography",emoji:"🌊"},
  {id:"arctic_ocean",en:"Arctic Ocean",zh:"北冰洋",cat:"geography",emoji:"🧊"},
  {id:"china",en:"China",zh:"中国",cat:"geography",emoji:"🇨🇳"},
  {id:"united_states",en:"United States",zh:"美国",cat:"geography",emoji:"🇺🇸"},
  {id:"united_kingdom",en:"United Kingdom",zh:"英国",cat:"geography",emoji:"🇬🇧"},
  {id:"france",en:"France",zh:"法国",cat:"geography",emoji:"🇫🇷"},
  {id:"germany",en:"Germany",zh:"德国",cat:"geography",emoji:"🇩🇪"},
  {id:"japan",en:"Japan",zh:"日本",cat:"geography",emoji:"🇯🇵"},
  {id:"korea",en:"Korea",zh:"韩国",cat:"geography",emoji:"🇰🇷"},
  {id:"india",en:"India",zh:"印度",cat:"geography",emoji:"🇮🇳"},
  {id:"brazil",en:"Brazil",zh:"巴西",cat:"geography",emoji:"🇧🇷"},
  {id:"russia",en:"Russia",zh:"俄罗斯",cat:"geography",emoji:"🇷🇺"},
  {id:"canada",en:"Canada",zh:"加拿大",cat:"geography",emoji:"🇨🇦"},
  {id:"mexico",en:"Mexico",zh:"墨西哥",cat:"geography",emoji:"🇲🇽"},
  {id:"italy",en:"Italy",zh:"意大利",cat:"geography",emoji:"🇮🇹"},
  {id:"spain",en:"Spain",zh:"西班牙",cat:"geography",emoji:"🇪🇸"},
  {id:"egypt",en:"Egypt",zh:"埃及",cat:"geography",emoji:"🇪🇬"},
  {id:"nigeria",en:"Nigeria",zh:"尼日利亚",cat:"geography",emoji:"🇳🇬"},
  {id:"south_africa",en:"South Africa",zh:"南非",cat:"geography",emoji:"🇿🇦"},
  {id:"argentina",en:"Argentina",zh:"阿根廷",cat:"geography",emoji:"🇦🇷"},
  {id:"indonesia",en:"Indonesia",zh:"印度尼西亚",cat:"geography",emoji:"🇮🇩"},
  {id:"saudi_arabia",en:"Saudi Arabia",zh:"沙特阿拉伯",cat:"geography",emoji:"🇸🇦"},
  {id:"turkey_country",en:"Turkey",zh:"土耳其",cat:"geography",emoji:"🇹🇷"},
  {id:"thailand",en:"Thailand",zh:"泰国",cat:"geography",emoji:"🇹🇭"},
  {id:"vietnam",en:"Vietnam",zh:"越南",cat:"geography",emoji:"🇻🇳"},
  {id:"philippines",en:"Philippines",zh:"菲律宾",cat:"geography",emoji:"🇵🇭"},
  {id:"pakistan",en:"Pakistan",zh:"巴基斯坦",cat:"geography",emoji:"🇵🇰"},
  {id:"bangladesh",en:"Bangladesh",zh:"孟加拉国",cat:"geography",emoji:"🇧🇩"},
  {id:"ukraine",en:"Ukraine",zh:"乌克兰",cat:"geography",emoji:"🇺🇦"},
  {id:"poland",en:"Poland",zh:"波兰",cat:"geography",emoji:"🇵🇱"},
  {id:"netherlands",en:"Netherlands",zh:"荷兰",cat:"geography",emoji:"🇳🇱"},
  {id:"beijing",en:"Beijing",zh:"北京",cat:"geography",emoji:"🏙️"},
  {id:"washington",en:"Washington",zh:"华盛顿",cat:"geography",emoji:"🏙️"},
  {id:"london",en:"London",zh:"伦敦",cat:"geography",emoji:"🏙️"},
  {id:"paris",en:"Paris",zh:"巴黎",cat:"geography",emoji:"🏙️"},
  {id:"berlin",en:"Berlin",zh:"柏林",cat:"geography",emoji:"🏙️"},
  {id:"tokyo",en:"Tokyo",zh:"东京",cat:"geography",emoji:"🏙️"},
  {id:"seoul",en:"Seoul",zh:"首尔",cat:"geography",emoji:"🏙️"},
  {id:"new_york",en:"New York",zh:"纽约",cat:"geography",emoji:"🏙️"},
  {id:"shanghai",en:"Shanghai",zh:"上海",cat:"geography",emoji:"🏙️"},
  {id:"sydney",en:"Sydney",zh:"悉尼",cat:"geography",emoji:"🏙️"},
  {id:"toronto",en:"Toronto",zh:"多伦多",cat:"geography",emoji:"🏙️"},
  {id:"dubai",en:"Dubai",zh:"迪拜",cat:"geography",emoji:"🏙️"},
  {id:"plateau",en:"plateau",zh:"高原",cat:"geography",emoji:"🏔️"},
  {id:"fjord",en:"fjord",zh:"峡湾",cat:"geography",emoji:"🌊"},
  {id:"lagoon",en:"lagoon",zh:"泻湖",cat:"geography",emoji:"🌊"},
  {id:"wetland",en:"wetland",zh:"湿地",cat:"geography",emoji:"🌿"},
  {id:"rainforest",en:"rainforest",zh:"雨林",cat:"geography",emoji:"🌴"},
  {id:"oasis",en:"oasis",zh:"绿洲",cat:"geography",emoji:"🌴"},
  {id:"archipelago",en:"archipelago",zh:"群岛",cat:"geography",emoji:"🏝️"},
  {id:"summit",en:"summit",zh:"山顶",cat:"geography",emoji:"⛰️"},
  {id:"ridge",en:"ridge",zh:"山脊",cat:"geography",emoji:"🏔️"},
  {id:"gorge",en:"gorge",zh:"峡谷",cat:"geography",emoji:"🏔️"},
  {id:"basin",en:"basin",zh:"盆地",cat:"geography",emoji:"🗺️"},
  {id:"strait",en:"strait",zh:"海峡",cat:"geography",emoji:"🌊"},
  {id:"gravity",en:"gravity",zh:"重力",cat:"science",emoji:"🍎"},
  {id:"force",en:"force",zh:"力",cat:"science",emoji:"💪"},
  {id:"energy",en:"energy",zh:"能量",cat:"science",emoji:"⚡"},
  {id:"matter",en:"matter",zh:"物质",cat:"science",emoji:"⚗️"},
  {id:"atom",en:"atom",zh:"原子",cat:"science",emoji:"⚛️"},
  {id:"molecule",en:"molecule",zh:"分子",cat:"science",emoji:"⚗️"},
  {id:"electron",en:"electron",zh:"电子",cat:"science",emoji:"⚡"},
  {id:"proton",en:"proton",zh:"质子",cat:"science",emoji:"⚛️"},
  {id:"neutron",en:"neutron",zh:"中子",cat:"science",emoji:"⚛️"},
  {id:"nucleus",en:"nucleus",zh:"细胞核",cat:"science",emoji:"🔬"},
  {id:"element",en:"element",zh:"元素",cat:"science",emoji:"⚗️"},
  {id:"compound",en:"compound",zh:"化合物",cat:"science",emoji:"⚗️"},
  {id:"mixture",en:"mixture",zh:"混合物",cat:"science",emoji:"⚗️"},
  {id:"solution",en:"solution",zh:"溶液",cat:"science",emoji:"💧"},
  {id:"solid",en:"solid",zh:"固体",cat:"science",emoji:"🧱"},
  {id:"liquid",en:"liquid",zh:"液体",cat:"science",emoji:"💧"},
  {id:"gas",en:"gas",zh:"气体",cat:"science",emoji:"💨"},
  {id:"plasma",en:"plasma",zh:"等离子体",cat:"science",emoji:"⚡"},
  {id:"heat_energy",en:"heat",zh:"热量",cat:"science",emoji:"🔥"},
  {id:"light_energy",en:"light",zh:"光",cat:"science",emoji:"💡"},
  {id:"sound_energy",en:"sound",zh:"声音",cat:"science",emoji:"🔊"},
  {id:"electricity",en:"electricity",zh:"电",cat:"science",emoji:"⚡"},
  {id:"magnetism",en:"magnetism",zh:"磁力",cat:"science",emoji:"🧲"},
  {id:"friction",en:"friction",zh:"摩擦力",cat:"science",emoji:"✋"},
  {id:"pressure",en:"pressure",zh:"压力",cat:"science",emoji:"⬇️"},
  {id:"velocity",en:"velocity",zh:"速度",cat:"science",emoji:"🏎️"},
  {id:"acceleration",en:"acceleration",zh:"加速度",cat:"science",emoji:"🚀"},
  {id:"momentum",en:"momentum",zh:"动量",cat:"science",emoji:"⚡"},
  {id:"mass",en:"mass",zh:"质量",cat:"science",emoji:"⚖️"},
  {id:"weight",en:"weight",zh:"重量",cat:"science",emoji:"⚖️"},
  {id:"volume_sci",en:"volume",zh:"体积",cat:"science",emoji:"📦"},
  {id:"density",en:"density",zh:"密度",cat:"science",emoji:"⚗️"},
  {id:"temperature",en:"temperature",zh:"温度",cat:"science",emoji:"🌡️"},
  {id:"radiation",en:"radiation",zh:"辐射",cat:"science",emoji:"☢️"},
  {id:"wavelength",en:"wavelength",zh:"波长",cat:"science",emoji:"〰️"},
  {id:"frequency",en:"frequency",zh:"频率",cat:"science",emoji:"📡"},
  {id:"reflection",en:"reflection",zh:"反射",cat:"science",emoji:"🪞"},
  {id:"refraction",en:"refraction",zh:"折射",cat:"science",emoji:"🌈"},
  {id:"spectrum",en:"spectrum",zh:"光谱",cat:"science",emoji:"🌈"},
  {id:"photon",en:"photon",zh:"光子",cat:"science",emoji:"✨"},
  {id:"cell_bio",en:"cell",zh:"细胞",cat:"science",emoji:"🔬"},
  {id:"membrane",en:"membrane",zh:"细胞膜",cat:"science",emoji:"🔬"},
  {id:"chromosome",en:"chromosome",zh:"染色体",cat:"science",emoji:"🧬"},
  {id:"gene",en:"gene",zh:"基因",cat:"science",emoji:"🧬"},
  {id:"dna",en:"DNA",zh:"脱氧核糖核酸",cat:"science",emoji:"🧬"},
  {id:"protein",en:"protein",zh:"蛋白质",cat:"science",emoji:"🥩"},
  {id:"enzyme",en:"enzyme",zh:"酶",cat:"science",emoji:"⚗️"},
  {id:"photosynthesis",en:"photosynthesis",zh:"光合作用",cat:"science",emoji:"🌱"},
  {id:"respiration",en:"respiration",zh:"呼吸作用",cat:"science",emoji:"😮‍💨"},
  {id:"evolution",en:"evolution",zh:"进化",cat:"science",emoji:"🦕"},
  {id:"adaptation",en:"adaptation",zh:"适应",cat:"science",emoji:"🦎"},
  {id:"ecosystem",en:"ecosystem",zh:"生态系统",cat:"science",emoji:"🌍"},
  {id:"habitat",en:"habitat",zh:"栖息地",cat:"science",emoji:"🏡"},
  {id:"biodiversity",en:"biodiversity",zh:"生物多样性",cat:"science",emoji:"🌿"},
  {id:"extinction",en:"extinction",zh:"灭绝",cat:"science",emoji:"🦕"},
  {id:"species",en:"species",zh:"物种",cat:"science",emoji:"🐾"},
  {id:"organism",en:"organism",zh:"生物",cat:"science",emoji:"🦠"},
  {id:"bacteria",en:"bacteria",zh:"细菌",cat:"science",emoji:"🦠"},
  {id:"virus",en:"virus",zh:"病毒",cat:"science",emoji:"🦠"},
  {id:"fungus",en:"fungus",zh:"真菌",cat:"science",emoji:"🍄"},
  {id:"parasite",en:"parasite",zh:"寄生虫",cat:"science",emoji:"🦠"},
  {id:"predator",en:"predator",zh:"捕食者",cat:"science",emoji:"🦁"},
  {id:"prey",en:"prey",zh:"猎物",cat:"science",emoji:"🐇"},
  {id:"food_chain",en:"food chain",zh:"食物链",cat:"science",emoji:"🔗"},
  {id:"pollination",en:"pollination",zh:"授粉",cat:"science",emoji:"🌺"},
  {id:"germination",en:"germination",zh:"发芽",cat:"science",emoji:"🌱"},
  {id:"metamorphosis",en:"metamorphosis",zh:"变态",cat:"science",emoji:"🦋"},
  {id:"camouflage",en:"camouflage",zh:"伪装",cat:"science",emoji:"🦎"},
  {id:"migration",en:"migration",zh:"迁徙",cat:"science",emoji:"🐦"},
  {id:"hibernation",en:"hibernation",zh:"冬眠",cat:"science",emoji:"🐻"},
  {id:"acid",en:"acid",zh:"酸",cat:"science",emoji:"⚗️"},
  {id:"base_chem",en:"base",zh:"碱",cat:"science",emoji:"⚗️"},
  {id:"reaction",en:"reaction",zh:"反应",cat:"science",emoji:"⚗️"},
  {id:"catalyst",en:"catalyst",zh:"催化剂",cat:"science",emoji:"⚗️"},
  {id:"oxidation",en:"oxidation",zh:"氧化",cat:"science",emoji:"🔥"},
  {id:"crystal",en:"crystal",zh:"晶体",cat:"science",emoji:"💎"},
  {id:"mineral",en:"mineral",zh:"矿物",cat:"science",emoji:"💎"},
  {id:"alloy",en:"alloy",zh:"合金",cat:"science",emoji:"⚙️"},
  {id:"carbon",en:"carbon",zh:"碳",cat:"science",emoji:"⚗️"},
  {id:"hydrogen",en:"hydrogen",zh:"氢",cat:"science",emoji:"⚗️"},
  {id:"oxygen",en:"oxygen",zh:"氧",cat:"science",emoji:"💨"},
  {id:"nitrogen",en:"nitrogen",zh:"氮",cat:"science",emoji:"⚗️"},
  {id:"periodic_table",en:"periodic table",zh:"元素周期表",cat:"science",emoji:"📊"},
  {id:"isotope",en:"isotope",zh:"同位素",cat:"science",emoji:"⚛️"},
  {id:"fusion",en:"fusion",zh:"聚变",cat:"science",emoji:"🌟"},
  {id:"fission",en:"fission",zh:"裂变",cat:"science",emoji:"⚡"},
  {id:"civilization",en:"civilization",zh:"文明",cat:"history",emoji:"🏛️"},
  {id:"medieval",en:"medieval",zh:"中世纪",cat:"history",emoji:"🏰"},
  {id:"revolution",en:"revolution",zh:"革命",cat:"history",emoji:"🔥"},
  {id:"empire",en:"empire",zh:"帝国",cat:"history",emoji:"👑"},
  {id:"dynasty",en:"dynasty",zh:"王朝",cat:"history",emoji:"👑"},
  {id:"republic",en:"republic",zh:"共和国",cat:"history",emoji:"🏛️"},
  {id:"democracy",en:"democracy",zh:"民主",cat:"history",emoji:"🗳️"},
  {id:"monarchy",en:"monarchy",zh:"君主制",cat:"history",emoji:"👑"},
  {id:"colonialism",en:"colonialism",zh:"殖民主义",cat:"history",emoji:"⛵"},
  {id:"independence",en:"independence",zh:"独立",cat:"history",emoji:"🗽"},
  {id:"constitution",en:"constitution",zh:"宪法",cat:"history",emoji:"📜"},
  {id:"treaty",en:"treaty",zh:"条约",cat:"history",emoji:"📜"},
  {id:"war",en:"war",zh:"战争",cat:"history",emoji:"⚔️"},
  {id:"peace",en:"peace",zh:"和平",cat:"history",emoji:"🕊️"},
  {id:"slavery",en:"slavery",zh:"奴隶制",cat:"history",emoji:"⛓️"},
  {id:"abolition",en:"abolition",zh:"废除",cat:"history",emoji:"✊"},
  {id:"immigration",en:"immigration",zh:"移民",cat:"history",emoji:"✈️"},
  {id:"refugee",en:"refugee",zh:"难民",cat:"history",emoji:"🏠"},
  {id:"culture",en:"culture",zh:"文化",cat:"history",emoji:"🎭"},
  {id:"tradition",en:"tradition",zh:"传统",cat:"history",emoji:"🎎"},
  {id:"heritage",en:"heritage",zh:"遗产",cat:"history",emoji:"🏛️"},
  {id:"artifact",en:"artifact",zh:"文物",cat:"history",emoji:"🏺"},
  {id:"archaeology",en:"archaeology",zh:"考古学",cat:"history",emoji:"🔍"},
  {id:"relic",en:"relic",zh:"遗迹",cat:"history",emoji:"🏺"},
  {id:"prehistoric",en:"prehistoric",zh:"史前",cat:"history",emoji:"🦕"},
  {id:"bronze_age",en:"Bronze Age",zh:"青铜时代",cat:"history",emoji:"🥉"},
  {id:"iron_age",en:"Iron Age",zh:"铁器时代",cat:"history",emoji:"⚙️"},
  {id:"renaissance",en:"Renaissance",zh:"文艺复兴",cat:"history",emoji:"🎨"},
  {id:"reformation",en:"Reformation",zh:"宗教改革",cat:"history",emoji:"✝️"},
  {id:"enlightenment",en:"Enlightenment",zh:"启蒙运动",cat:"history",emoji:"💡"},
  {id:"industrial_revolution",en:"Industrial Revolution",zh:"工业革命",cat:"history",emoji:"🏭"},
  {id:"globalization",en:"globalization",zh:"全球化",cat:"history",emoji:"🌍"},
  {id:"government",en:"government",zh:"政府",cat:"government",emoji:"🏛️"},
  {id:"parliament",en:"parliament",zh:"议会",cat:"government",emoji:"🏛️"},
  {id:"congress",en:"congress",zh:"国会",cat:"government",emoji:"🏛️"},
  {id:"senate",en:"senate",zh:"参议院",cat:"government",emoji:"🏛️"},
  {id:"legislation",en:"legislation",zh:"立法",cat:"government",emoji:"📜"},
  {id:"judiciary",en:"judiciary",zh:"司法",cat:"government",emoji:"⚖️"},
  {id:"executive",en:"executive",zh:"行政",cat:"government",emoji:"👔"},
  {id:"legislative",en:"legislative",zh:"立法的",cat:"government",emoji:"📜"},
  {id:"bill_gov",en:"bill",zh:"法案",cat:"government",emoji:"📋"},
  {id:"law",en:"law",zh:"法律",cat:"government",emoji:"⚖️"},
  {id:"amendment",en:"amendment",zh:"修正案",cat:"government",emoji:"📜"},
  {id:"veto",en:"veto",zh:"否决权",cat:"government",emoji:"🚫"},
  {id:"sovereignty",en:"sovereignty",zh:"主权",cat:"government",emoji:"👑"},
  {id:"diplomat",en:"diplomat",zh:"外交官",cat:"government",emoji:"🤝"},
  {id:"embassy",en:"embassy",zh:"大使馆",cat:"government",emoji:"🏛️"},
  {id:"ambassador",en:"ambassador",zh:"大使",cat:"government",emoji:"🤝"},
  {id:"alliance",en:"alliance",zh:"联盟",cat:"government",emoji:"🤝"},
  {id:"united_nations",en:"United Nations",zh:"联合国",cat:"government",emoji:"🌍"},
  {id:"federal",en:"federal",zh:"联邦",cat:"government",emoji:"🏛️"},
  {id:"election",en:"election",zh:"选举",cat:"government",emoji:"🗳️"},
  {id:"campaign",en:"campaign",zh:"竞选",cat:"government",emoji:"📢"},
  {id:"referendum",en:"referendum",zh:"公投",cat:"government",emoji:"🗳️"},
  {id:"citizen",en:"citizen",zh:"公民",cat:"government",emoji:"🪪"},
  {id:"rights",en:"rights",zh:"权利",cat:"government",emoji:"✊"},
  {id:"freedom",en:"freedom",zh:"自由",cat:"government",emoji:"🗽"},
  {id:"equality",en:"equality",zh:"平等",cat:"government",emoji:"⚖️"},
  {id:"justice_gov",en:"justice",zh:"正义",cat:"government",emoji:"⚖️"},
  {id:"protest",en:"protest",zh:"抗议",cat:"government",emoji:"✊"},
  {id:"policy",en:"policy",zh:"政策",cat:"government",emoji:"📋"},
  {id:"tax",en:"tax",zh:"税",cat:"government",emoji:"💰"},
  {id:"economy",en:"economy",zh:"经济",cat:"business",emoji:"📈"},
  {id:"market_econ",en:"market",zh:"市场",cat:"business",emoji:"🏪"},
  {id:"trade",en:"trade",zh:"贸易",cat:"business",emoji:"🤝"},
  {id:"commerce",en:"commerce",zh:"商业",cat:"business",emoji:"💼"},
  {id:"industry",en:"industry",zh:"工业",cat:"business",emoji:"🏭"},
  {id:"agriculture",en:"agriculture",zh:"农业",cat:"business",emoji:"🌾"},
  {id:"manufacturing",en:"manufacturing",zh:"制造业",cat:"business",emoji:"🏭"},
  {id:"finance",en:"finance",zh:"金融",cat:"business",emoji:"💰"},
  {id:"currency",en:"currency",zh:"货币",cat:"business",emoji:"💵"},
  {id:"inflation",en:"inflation",zh:"通货膨胀",cat:"business",emoji:"📈"},
  {id:"recession",en:"recession",zh:"经济衰退",cat:"business",emoji:"📉"},
  {id:"stock",en:"stock",zh:"股票",cat:"business",emoji:"📈"},
  {id:"investment",en:"investment",zh:"投资",cat:"business",emoji:"💰"},
  {id:"profit",en:"profit",zh:"利润",cat:"business",emoji:"💰"},
  {id:"loss",en:"loss",zh:"损失",cat:"business",emoji:"📉"},
  {id:"revenue",en:"revenue",zh:"收入",cat:"business",emoji:"💰"},
  {id:"budget",en:"budget",zh:"预算",cat:"business",emoji:"📊"},
  {id:"tariff",en:"tariff",zh:"关税",cat:"business",emoji:"🚢"},
  {id:"export",en:"export",zh:"出口",cat:"business",emoji:"🚢"},
  {id:"import",en:"import",zh:"进口",cat:"business",emoji:"🚢"},
  {id:"supply",en:"supply",zh:"供应",cat:"business",emoji:"📦"},
  {id:"demand",en:"demand",zh:"需求",cat:"business",emoji:"📊"},
  {id:"competition",en:"competition",zh:"竞争",cat:"business",emoji:"🏆"},
  {id:"monopoly",en:"monopoly",zh:"垄断",cat:"business",emoji:"🎩"},
  {id:"entrepreneur",en:"entrepreneur",zh:"企业家",cat:"business",emoji:"💡"},
  {id:"startup",en:"startup",zh:"初创公司",cat:"business",emoji:"🚀"},
  {id:"corporation",en:"corporation",zh:"公司",cat:"business",emoji:"🏢"},
  {id:"salary",en:"salary",zh:"薪资",cat:"business",emoji:"💰"},
  {id:"contract",en:"contract",zh:"合同",cat:"business",emoji:"📝"},
  {id:"insurance",en:"insurance",zh:"保险",cat:"business",emoji:"🛡️"},
  {id:"mortgage",en:"mortgage",zh:"按揭",cat:"business",emoji:"🏠"},
  {id:"interest",en:"interest",zh:"利息",cat:"business",emoji:"💰"},
  {id:"anatomy",en:"anatomy",zh:"解剖学",cat:"health",emoji:"🦴"},
  {id:"physiology",en:"physiology",zh:"生理学",cat:"health",emoji:"🧬"},
  {id:"diagnosis",en:"diagnosis",zh:"诊断",cat:"health",emoji:"🩺"},
  {id:"treatment",en:"treatment",zh:"治疗",cat:"health",emoji:"💊"},
  {id:"surgery",en:"surgery",zh:"手术",cat:"health",emoji:"🏥"},
  {id:"therapy",en:"therapy",zh:"疗法",cat:"health",emoji:"🧘"},
  {id:"antibiotic",en:"antibiotic",zh:"抗生素",cat:"health",emoji:"💊"},
  {id:"symptom",en:"symptom",zh:"症状",cat:"health",emoji:"🤒"},
  {id:"disease",en:"disease",zh:"疾病",cat:"health",emoji:"🦠"},
  {id:"infection",en:"infection",zh:"感染",cat:"health",emoji:"🦠"},
  {id:"inflammation",en:"inflammation",zh:"炎症",cat:"health",emoji:"🔥"},
  {id:"immune_system",en:"immune system",zh:"免疫系统",cat:"health",emoji:"🛡️"},
  {id:"nervous_system",en:"nervous system",zh:"神经系统",cat:"health",emoji:"🧠"},
  {id:"cardiovascular",en:"cardiovascular",zh:"心血管",cat:"health",emoji:"❤️"},
  {id:"respiratory",en:"respiratory",zh:"呼吸",cat:"health",emoji:"😮‍💨"},
  {id:"digestive",en:"digestive",zh:"消化",cat:"health",emoji:"🫃"},
  {id:"skeleton",en:"skeleton",zh:"骨骼",cat:"health",emoji:"💀"},
  {id:"organ",en:"organ",zh:"器官",cat:"health",emoji:"🫀"},
  {id:"tissue",en:"tissue",zh:"组织",cat:"health",emoji:"🔬"},
  {id:"artery",en:"artery",zh:"动脉",cat:"health",emoji:"❤️"},
  {id:"vein",en:"vein",zh:"静脉",cat:"health",emoji:"💙"},
  {id:"capillary",en:"capillary",zh:"毛细血管",cat:"health",emoji:"🩸"},
  {id:"blood_pressure",en:"blood pressure",zh:"血压",cat:"health",emoji:"❤️"},
  {id:"ultrasound",en:"ultrasound",zh:"超声波",cat:"health",emoji:"📡"},
  {id:"anesthesia",en:"anesthesia",zh:"麻醉",cat:"health",emoji:"💉"},
  {id:"suture",en:"suture",zh:"缝合",cat:"health",emoji:"🩹"},
  {id:"metabolism",en:"metabolism",zh:"新陈代谢",cat:"health",emoji:"⚡"},
  {id:"obesity",en:"obesity",zh:"肥胖",cat:"health",emoji:"⚖️"},
  {id:"diabetes",en:"diabetes",zh:"糖尿病",cat:"health",emoji:"💉"},
  {id:"cancer",en:"cancer",zh:"癌症",cat:"health",emoji:"🎗️"},
  {id:"stroke",en:"stroke",zh:"中风",cat:"health",emoji:"🧠"},
  {id:"heart_attack",en:"heart attack",zh:"心脏病发作",cat:"health",emoji:"❤️"},
  {id:"carbohydrate",en:"carbohydrate",zh:"碳水化合物",cat:"health",emoji:"🍞"},
  {id:"fat_nutrition",en:"fat",zh:"脂肪",cat:"health",emoji:"🧈"},
  {id:"calorie",en:"calorie",zh:"卡路里",cat:"health",emoji:"🔥"},
  {id:"hydration",en:"hydration",zh:"水分补充",cat:"health",emoji:"💧"},
  {id:"fitness",en:"fitness",zh:"健身",cat:"health",emoji:"🏋️"},
  {id:"mental_health",en:"mental health",zh:"心理健康",cat:"health",emoji:"🧠"},
  {id:"meditation",en:"meditation",zh:"冥想",cat:"health",emoji:"🧘"},
  {id:"hygiene",en:"hygiene",zh:"卫生",cat:"health",emoji:"🧼"},
  {id:"climate_change",en:"climate change",zh:"气候变化",cat:"environment",emoji:"🌡️"},
  {id:"global_warming",en:"global warming",zh:"全球变暖",cat:"environment",emoji:"🌍"},
  {id:"greenhouse_effect",en:"greenhouse effect",zh:"温室效应",cat:"environment",emoji:"🌡️"},
  {id:"carbon_footprint",en:"carbon footprint",zh:"碳足迹",cat:"environment",emoji:"👣"},
  {id:"renewable_energy",en:"renewable energy",zh:"可再生能源",cat:"environment",emoji:"♻️"},
  {id:"solar_power",en:"solar power",zh:"太阳能",cat:"environment",emoji:"☀️"},
  {id:"wind_power",en:"wind power",zh:"风能",cat:"environment",emoji:"💨"},
  {id:"hydropower",en:"hydropower",zh:"水力发电",cat:"environment",emoji:"💧"},
  {id:"nuclear_energy",en:"nuclear energy",zh:"核能",cat:"environment",emoji:"⚡"},
  {id:"fossil_fuel",en:"fossil fuel",zh:"化石燃料",cat:"environment",emoji:"⛽"},
  {id:"coal",en:"coal",zh:"煤炭",cat:"environment",emoji:"⛏️"},
  {id:"petroleum",en:"petroleum",zh:"石油",cat:"environment",emoji:"🛢️"},
  {id:"natural_gas",en:"natural gas",zh:"天然气",cat:"environment",emoji:"🔥"},
  {id:"pollution",en:"pollution",zh:"污染",cat:"environment",emoji:"🏭"},
  {id:"air_pollution",en:"air pollution",zh:"空气污染",cat:"environment",emoji:"😷"},
  {id:"water_pollution",en:"water pollution",zh:"水污染",cat:"environment",emoji:"💧"},
  {id:"recycling",en:"recycling",zh:"回收",cat:"environment",emoji:"♻️"},
  {id:"waste",en:"waste",zh:"废物",cat:"environment",emoji:"🗑️"},
  {id:"compost",en:"compost",zh:"堆肥",cat:"environment",emoji:"🌱"},
  {id:"biodegradable",en:"biodegradable",zh:"可降解",cat:"environment",emoji:"🌿"},
  {id:"conservation",en:"conservation",zh:"保护",cat:"environment",emoji:"🌍"},
  {id:"deforestation",en:"deforestation",zh:"森林砍伐",cat:"environment",emoji:"🌲"},
  {id:"reforestation",en:"reforestation",zh:"植树造林",cat:"environment",emoji:"🌲"},
  {id:"endangered",en:"endangered",zh:"濒危",cat:"environment",emoji:"🦕"},
  {id:"sustainable",en:"sustainable",zh:"可持续",cat:"environment",emoji:"🌱"},
  {id:"organic",en:"organic",zh:"有机",cat:"environment",emoji:"🌿"},
  {id:"ozone_layer",en:"ozone layer",zh:"臭氧层",cat:"environment",emoji:"🌍"},
  {id:"acid_rain",en:"acid rain",zh:"酸雨",cat:"environment",emoji:"🌧️"},
  {id:"wildfire",en:"wildfire",zh:"野火",cat:"environment",emoji:"🔥"},
  {id:"tsunami",en:"tsunami",zh:"海啸",cat:"environment",emoji:"🌊"},
  {id:"sea_level",en:"sea level",zh:"海平面",cat:"environment",emoji:"🌊"},
  {id:"permafrost",en:"permafrost",zh:"永久冻土",cat:"environment",emoji:"🧊"},
  {id:"plastic",en:"plastic",zh:"塑料",cat:"environment",emoji:"🧴"},
  {id:"emission",en:"emission",zh:"排放",cat:"environment",emoji:"🏭"},
  {id:"painting",en:"painting",zh:"绘画",cat:"arts",emoji:"🖼️"},
  {id:"sculpture",en:"sculpture",zh:"雕塑",cat:"arts",emoji:"🗿"},
  {id:"photography",en:"photography",zh:"摄影",cat:"arts",emoji:"📷"},
  {id:"film",en:"film",zh:"电影",cat:"arts",emoji:"🎬"},
  {id:"ballet",en:"ballet",zh:"芭蕾舞",cat:"arts",emoji:"🩰"},
  {id:"exhibit",en:"exhibit",zh:"展览",cat:"arts",emoji:"🖼️"},
  {id:"gallery",en:"gallery",zh:"画廊",cat:"arts",emoji:"🖼️"},
  {id:"auction",en:"auction",zh:"拍卖",cat:"arts",emoji:"🔨"},
  {id:"masterpiece",en:"masterpiece",zh:"杰作",cat:"arts",emoji:"🎨"},
  {id:"impressionism",en:"Impressionism",zh:"印象派",cat:"arts",emoji:"🎨"},
  {id:"cubism",en:"Cubism",zh:"立体主义",cat:"arts",emoji:"🎨"},
  {id:"abstract_art",en:"abstract art",zh:"抽象艺术",cat:"arts",emoji:"🎨"},
  {id:"perspective",en:"perspective",zh:"透视",cat:"arts",emoji:"🔍"},
  {id:"composition",en:"composition",zh:"构图",cat:"arts",emoji:"🎨"},
  {id:"texture",en:"texture",zh:"纹理",cat:"arts",emoji:"🖐️"},
  {id:"contrast",en:"contrast",zh:"对比",cat:"arts",emoji:"⚫"},
  {id:"harmony",en:"harmony",zh:"和谐",cat:"arts",emoji:"🎵"},
  {id:"proportion",en:"proportion",zh:"比例",cat:"arts",emoji:"📐"},
  {id:"symmetry",en:"symmetry",zh:"对称",cat:"arts",emoji:"🪞"},
  {id:"fresco",en:"fresco",zh:"壁画",cat:"arts",emoji:"🖼️"},
  {id:"mosaic",en:"mosaic",zh:"马赛克",cat:"arts",emoji:"🔲"},
  {id:"calligraphy",en:"calligraphy",zh:"书法",cat:"arts",emoji:"✍️"},
  {id:"typography",en:"typography",zh:"排版",cat:"arts",emoji:"🔤"},
  {id:"graphic_design",en:"graphic design",zh:"平面设计",cat:"arts",emoji:"🎨"},
  {id:"architecture",en:"architecture",zh:"建筑学",cat:"arts",emoji:"🏛️"},
  {id:"urban_planning",en:"urban planning",zh:"城市规划",cat:"arts",emoji:"🏙️"},
  {id:"literature",en:"literature",zh:"文学",cat:"academic",emoji:"📚"},
  {id:"poetry",en:"poetry",zh:"诗歌",cat:"academic",emoji:"📝"},
  {id:"prose",en:"prose",zh:"散文",cat:"academic",emoji:"📖"},
  {id:"fiction",en:"fiction",zh:"虚构",cat:"academic",emoji:"📖"},
  {id:"nonfiction",en:"nonfiction",zh:"非虚构",cat:"academic",emoji:"📖"},
  {id:"biography",en:"biography",zh:"传记",cat:"academic",emoji:"📖"},
  {id:"autobiography",en:"autobiography",zh:"自传",cat:"academic",emoji:"📖"},
  {id:"fairy_tale",en:"fairy tale",zh:"童话",cat:"academic",emoji:"🧚"},
  {id:"myth",en:"myth",zh:"神话",cat:"academic",emoji:"🏛️"},
  {id:"legend",en:"legend",zh:"传说",cat:"academic",emoji:"📜"},
  {id:"fable",en:"fable",zh:"寓言",cat:"academic",emoji:"🐢"},
  {id:"metaphor",en:"metaphor",zh:"比喻",cat:"academic",emoji:"💬"},
  {id:"simile",en:"simile",zh:"明喻",cat:"academic",emoji:"💬"},
  {id:"alliteration",en:"alliteration",zh:"头韵",cat:"academic",emoji:"🔤"},
  {id:"onomatopoeia",en:"onomatopoeia",zh:"拟声词",cat:"academic",emoji:"🔊"},
  {id:"stanza",en:"stanza",zh:"诗节",cat:"academic",emoji:"📝"},
  {id:"narrative",en:"narrative",zh:"叙述",cat:"academic",emoji:"📖"},
  {id:"dialogue",en:"dialogue",zh:"对话",cat:"academic",emoji:"💬"},
  {id:"protagonist",en:"protagonist",zh:"主角",cat:"academic",emoji:"🦸"},
  {id:"antagonist",en:"antagonist",zh:"反派",cat:"academic",emoji:"🦹"},
  {id:"conflict",en:"conflict",zh:"冲突",cat:"academic",emoji:"⚔️"},
  {id:"resolution",en:"resolution",zh:"解决",cat:"academic",emoji:"✅"},
  {id:"climax",en:"climax",zh:"高潮",cat:"academic",emoji:"📈"},
  {id:"genre",en:"genre",zh:"体裁",cat:"academic",emoji:"📚"},
  {id:"thesis",en:"thesis",zh:"论文",cat:"academic",emoji:"📝"},
  {id:"argument",en:"argument",zh:"论点",cat:"academic",emoji:"💬"},
  {id:"evidence",en:"evidence",zh:"证据",cat:"academic",emoji:"🔍"},
  {id:"conclusion_acad",en:"conclusion",zh:"结论",cat:"academic",emoji:"✅"},
  {id:"bibliography",en:"bibliography",zh:"参考书目",cat:"academic",emoji:"📚"},
  {id:"citation",en:"citation",zh:"引用",cat:"academic",emoji:"📝"},
  {id:"analysis",en:"analysis",zh:"分析",cat:"academic",emoji:"🔍"},
  {id:"interpretation",en:"interpretation",zh:"解释",cat:"academic",emoji:"💡"},
  {id:"statistics",en:"statistics",zh:"统计学",cat:"academic",emoji:"📊"},
  {id:"probability",en:"probability",zh:"概率",cat:"academic",emoji:"🎲"},
  {id:"geometry",en:"geometry",zh:"几何",cat:"academic",emoji:"📐"},
  {id:"algebra",en:"algebra",zh:"代数",cat:"academic",emoji:"✖️"},
  {id:"calculus",en:"calculus",zh:"微积分",cat:"academic",emoji:"∫"},
  {id:"trigonometry",en:"trigonometry",zh:"三角学",cat:"academic",emoji:"📐"},
  {id:"variable",en:"variable",zh:"变量",cat:"academic",emoji:"❓"},
  {id:"equation",en:"equation",zh:"方程式",cat:"academic",emoji:"➗"},
  {id:"formula",en:"formula",zh:"公式",cat:"academic",emoji:"📐"},
  {id:"graph",en:"graph",zh:"图表",cat:"academic",emoji:"📊"},
  {id:"magnificent",en:"magnificent",zh:"壮观",cat:"adjectives",emoji:"🌟"},
  {id:"extraordinary",en:"extraordinary",zh:"非凡",cat:"adjectives",emoji:"✨"},
  {id:"tremendous",en:"tremendous",zh:"巨大",cat:"adjectives",emoji:"💥"},
  {id:"remarkable",en:"remarkable",zh:"非凡",cat:"adjectives",emoji:"🌟"},
  {id:"spectacular",en:"spectacular",zh:"壮观",cat:"adjectives",emoji:"🎆"},
  {id:"phenomenal",en:"phenomenal",zh:"惊人",cat:"adjectives",emoji:"🤯"},
  {id:"exceptional",en:"exceptional",zh:"卓越",cat:"adjectives",emoji:"🏆"},
  {id:"outstanding",en:"outstanding",zh:"杰出",cat:"adjectives",emoji:"⭐"},
  {id:"impressive",en:"impressive",zh:"令人印象深刻",cat:"adjectives",emoji:"👏"},
  {id:"sophisticated",en:"sophisticated",zh:"复杂",cat:"adjectives",emoji:"🎩"},
  {id:"elegant",en:"elegant",zh:"优雅",cat:"adjectives",emoji:"🌹"},
  {id:"graceful",en:"graceful",zh:"优美",cat:"adjectives",emoji:"🩰"},
  {id:"majestic",en:"majestic",zh:"雄伟",cat:"adjectives",emoji:"🏔️"},
  {id:"splendid",en:"splendid",zh:"辉煌",cat:"adjectives",emoji:"✨"},
  {id:"brilliant",en:"brilliant",zh:"辉煌",cat:"adjectives",emoji:"💡"},
  {id:"radiant",en:"radiant",zh:"光彩照人",cat:"adjectives",emoji:"☀️"},
  {id:"vibrant",en:"vibrant",zh:"充满活力",cat:"adjectives",emoji:"🌈"},
  {id:"vivid",en:"vivid",zh:"生动",cat:"adjectives",emoji:"🎨"},
  {id:"luminous",en:"luminous",zh:"发光",cat:"adjectives",emoji:"💡"},
  {id:"transparent",en:"transparent",zh:"透明",cat:"adjectives",emoji:"🪟"},
  {id:"translucent",en:"translucent",zh:"半透明",cat:"adjectives",emoji:"🪟"},
  {id:"opaque",en:"opaque",zh:"不透明",cat:"adjectives",emoji:"🧱"},
  {id:"flexible",en:"flexible",zh:"灵活",cat:"adjectives",emoji:"🤸"},
  {id:"rigid",en:"rigid",zh:"僵硬",cat:"adjectives",emoji:"🪨"},
  {id:"fragile",en:"fragile",zh:"易碎",cat:"adjectives",emoji:"🥚"},
  {id:"durable",en:"durable",zh:"耐用",cat:"adjectives",emoji:"🏋️"},
  {id:"resistant",en:"resistant",zh:"耐",cat:"adjectives",emoji:"🛡️"},
  {id:"vulnerable",en:"vulnerable",zh:"脆弱",cat:"adjectives",emoji:"🥺"},
  {id:"immune",en:"immune",zh:"免疫",cat:"adjectives",emoji:"🛡️"},
  {id:"sensitive",en:"sensitive",zh:"敏感",cat:"adjectives",emoji:"🌸"},
  {id:"perceptive",en:"perceptive",zh:"有洞察力",cat:"adjectives",emoji:"🔍"},
  {id:"analytical",en:"analytical",zh:"分析性",cat:"adjectives",emoji:"🔬"},
  {id:"logical",en:"logical",zh:"逻辑性",cat:"adjectives",emoji:"🧠"},
  {id:"rational",en:"rational",zh:"理性",cat:"adjectives",emoji:"🧠"},
  {id:"irrational",en:"irrational",zh:"非理性",cat:"adjectives",emoji:"🌀"},
  {id:"objective",en:"objective",zh:"客观",cat:"adjectives",emoji:"⚖️"},
  {id:"subjective",en:"subjective",zh:"主观",cat:"adjectives",emoji:"💭"},
  {id:"comprehensive",en:"comprehensive",zh:"全面",cat:"adjectives",emoji:"📚"},
  {id:"thorough",en:"thorough",zh:"彻底",cat:"adjectives",emoji:"🔍"},
  {id:"precise",en:"precise",zh:"精确",cat:"adjectives",emoji:"🎯"},
  {id:"accurate",en:"accurate",zh:"准确",cat:"adjectives",emoji:"✅"},
  {id:"approximate",en:"approximate",zh:"大约",cat:"adjectives",emoji:"≈"},
  {id:"vague",en:"vague",zh:"模糊",cat:"adjectives",emoji:"🌫️"},
  {id:"ambiguous",en:"ambiguous",zh:"歧义",cat:"adjectives",emoji:"❓"},
  {id:"explicit",en:"explicit",zh:"明确",cat:"adjectives",emoji:"✅"},
  {id:"implicit",en:"implicit",zh:"隐含",cat:"adjectives",emoji:"💭"},
  {id:"conventional",en:"conventional",zh:"传统",cat:"adjectives",emoji:"📋"},
  {id:"unconventional",en:"unconventional",zh:"非传统",cat:"adjectives",emoji:"🔀"},
  {id:"innovative",en:"innovative",zh:"创新",cat:"adjectives",emoji:"💡"},
  {id:"conservative",en:"conservative",zh:"保守",cat:"adjectives",emoji:"🛡️"},
  {id:"progressive",en:"progressive",zh:"进步",cat:"adjectives",emoji:"📈"},
  {id:"radical",en:"radical",zh:"激进",cat:"adjectives",emoji:"🔥"},
  {id:"moderate",en:"moderate",zh:"温和",cat:"adjectives",emoji:"⚖️"},
  {id:"essential",en:"essential",zh:"必要",cat:"adjectives",emoji:"⭐"},
  {id:"fundamental",en:"fundamental",zh:"基本",cat:"adjectives",emoji:"🏗️"},
  {id:"superficial",en:"superficial",zh:"肤浅",cat:"adjectives",emoji:"👁️"},
  {id:"profound",en:"profound",zh:"深刻",cat:"adjectives",emoji:"🌊"},
  {id:"significant",en:"significant",zh:"重要",cat:"adjectives",emoji:"❗"},
  {id:"trivial",en:"trivial",zh:"微不足道",cat:"adjectives",emoji:"🐜"},
  {id:"relevant",en:"relevant",zh:"相关",cat:"adjectives",emoji:"🔗"},
  {id:"irrelevant",en:"irrelevant",zh:"无关",cat:"adjectives",emoji:"✂️"},
  {id:"effective",en:"effective",zh:"有效",cat:"adjectives",emoji:"✅"},
  {id:"efficient",en:"efficient",zh:"高效",cat:"adjectives",emoji:"⚡"},
  {id:"productive",en:"productive",zh:"高产",cat:"adjectives",emoji:"📈"},
  {id:"constructive",en:"constructive",zh:"建设性",cat:"adjectives",emoji:"🏗️"},
  {id:"destructive",en:"destructive",zh:"破坏性",cat:"adjectives",emoji:"💥"},
  {id:"beneficial",en:"beneficial",zh:"有益",cat:"adjectives",emoji:"✅"},
  {id:"harmful",en:"harmful",zh:"有害",cat:"adjectives",emoji:"⚠️"},
  {id:"controversial",en:"controversial",zh:"有争议",cat:"adjectives",emoji:"🔥"},
  {id:"inevitable",en:"inevitable",zh:"不可避免",cat:"adjectives",emoji:"⏳"},
  {id:"establish",en:"establish",zh:"建立",cat:"verbs",emoji:"🏗️"},
  {id:"develop",en:"develop",zh:"发展",cat:"verbs",emoji:"📈"},
  {id:"implement",en:"implement",zh:"实施",cat:"verbs",emoji:"🛠️"},
  {id:"maintain",en:"maintain",zh:"维护",cat:"verbs",emoji:"🔧"},
  {id:"improve",en:"improve",zh:"改善",cat:"verbs",emoji:"📈"},
  {id:"enhance",en:"enhance",zh:"增强",cat:"verbs",emoji:"⬆️"},
  {id:"reduce",en:"reduce",zh:"减少",cat:"verbs",emoji:"⬇️"},
  {id:"eliminate",en:"eliminate",zh:"消除",cat:"verbs",emoji:"🗑️"},
  {id:"prevent",en:"prevent",zh:"预防",cat:"verbs",emoji:"🛡️"},
  {id:"detect",en:"detect",zh:"检测",cat:"verbs",emoji:"🔍"},
  {id:"identify",en:"identify",zh:"识别",cat:"verbs",emoji:"🏷️"},
  {id:"analyze",en:"analyze",zh:"分析",cat:"verbs",emoji:"🔬"},
  {id:"evaluate",en:"evaluate",zh:"评估",cat:"verbs",emoji:"📊"},
  {id:"assess",en:"assess",zh:"评定",cat:"verbs",emoji:"📋"},
  {id:"determine",en:"determine",zh:"确定",cat:"verbs",emoji:"✅"},
  {id:"demonstrate",en:"demonstrate",zh:"展示",cat:"verbs",emoji:"👐"},
  {id:"illustrate",en:"illustrate",zh:"说明",cat:"verbs",emoji:"🖼️"},
  {id:"indicate",en:"indicate",zh:"表明",cat:"verbs",emoji:"👆"},
  {id:"suggest",en:"suggest",zh:"建议",cat:"verbs",emoji:"💡"},
  {id:"recommend",en:"recommend",zh:"推荐",cat:"verbs",emoji:"👍"},
  {id:"propose",en:"propose",zh:"提议",cat:"verbs",emoji:"📋"},
  {id:"examine",en:"examine",zh:"检查",cat:"verbs",emoji:"🔍"},
  {id:"investigate",en:"investigate",zh:"调查",cat:"verbs",emoji:"🔍"},
  {id:"explore",en:"explore",zh:"探索",cat:"verbs",emoji:"🌍"},
  {id:"discover",en:"discover",zh:"发现",cat:"verbs",emoji:"💡"},
  {id:"invent",en:"invent",zh:"发明",cat:"verbs",emoji:"💡"},
  {id:"design",en:"design",zh:"设计",cat:"verbs",emoji:"✏️"},
  {id:"construct",en:"construct",zh:"建造",cat:"verbs",emoji:"🏗️"},
  {id:"produce",en:"produce",zh:"生产",cat:"verbs",emoji:"🏭"},
  {id:"generate",en:"generate",zh:"产生",cat:"verbs",emoji:"⚡"},
  {id:"transform",en:"transform",zh:"转变",cat:"verbs",emoji:"🔄"},
  {id:"convert",en:"convert",zh:"转换",cat:"verbs",emoji:"🔄"},
  {id:"transfer",en:"transfer",zh:"转移",cat:"verbs",emoji:"📦"},
  {id:"communicate",en:"communicate",zh:"沟通",cat:"verbs",emoji:"💬"},
  {id:"negotiate",en:"negotiate",zh:"谈判",cat:"verbs",emoji:"🤝"},
  {id:"collaborate",en:"collaborate",zh:"合作",cat:"verbs",emoji:"🤝"},
  {id:"cooperate",en:"cooperate",zh:"合作",cat:"verbs",emoji:"🤝"},
  {id:"contribute",en:"contribute",zh:"贡献",cat:"verbs",emoji:"🎁"},
  {id:"participate",en:"participate",zh:"参与",cat:"verbs",emoji:"🙋"},
  {id:"coordinate",en:"coordinate",zh:"协调",cat:"verbs",emoji:"🗂️"},
  {id:"monitor",en:"monitor",zh:"监控",cat:"verbs",emoji:"👁️"},
  {id:"evaluate_v",en:"evaluate",zh:"评估",cat:"verbs",emoji:"📊"},
  {id:"report",en:"report",zh:"报告",cat:"verbs",emoji:"📋"},
  {id:"document",en:"document",zh:"记录",cat:"verbs",emoji:"📝"},
  {id:"publish",en:"publish",zh:"出版",cat:"verbs",emoji:"📖"},
  {id:"distribute",en:"distribute",zh:"分发",cat:"verbs",emoji:"📦"},
  {id:"promote",en:"promote",zh:"推广",cat:"verbs",emoji:"📢"},
  {id:"advertise",en:"advertise",zh:"广告",cat:"verbs",emoji:"📢"},
  {id:"negotiate_v",en:"negotiate",zh:"协商",cat:"verbs",emoji:"🤝"},
  {id:"calculate",en:"calculate",zh:"计算",cat:"verbs",emoji:"🧮"},
  {id:"estimate",en:"estimate",zh:"估计",cat:"verbs",emoji:"≈"},
  {id:"predict",en:"predict",zh:"预测",cat:"verbs",emoji:"🔮"},
  {id:"forecast",en:"forecast",zh:"预报",cat:"verbs",emoji:"🌤️"},
  {id:"simulate",en:"simulate",zh:"模拟",cat:"verbs",emoji:"💻"},
  {id:"model",en:"model",zh:"建模",cat:"verbs",emoji:"📊"},
  {id:"classify",en:"classify",zh:"分类",cat:"verbs",emoji:"🗂️"},
  {id:"categorize",en:"categorize",zh:"归类",cat:"verbs",emoji:"📁"},
  {id:"interpret",en:"interpret",zh:"解释",cat:"verbs",emoji:"💡"},
  {id:"summarize",en:"summarize",zh:"总结",cat:"verbs",emoji:"📋"},
  {id:"criticize",en:"criticize",zh:"批评",cat:"verbs",emoji:"💬"},
  {id:"defend",en:"defend",zh:"捍卫",cat:"verbs",emoji:"🛡️"},
  {id:"oppose",en:"oppose",zh:"反对",cat:"verbs",emoji:"✋"},
  {id:"reject",en:"reject",zh:"拒绝",cat:"verbs",emoji:"❌"},
  {id:"accept",en:"accept",zh:"接受",cat:"verbs",emoji:"✅"},
  {id:"confirm",en:"confirm",zh:"确认",cat:"verbs",emoji:"✅"},
  {id:"deny",en:"deny",zh:"否认",cat:"verbs",emoji:"❌"},
  {id:"approve",en:"approve",zh:"批准",cat:"verbs",emoji:"✅"},
  {id:"refuse",en:"refuse",zh:"拒绝",cat:"verbs",emoji:"❌"},
  {id:"prohibit",en:"prohibit",zh:"禁止",cat:"verbs",emoji:"🚫"},
  {id:"require",en:"require",zh:"要求",cat:"verbs",emoji:"📋"},
  {id:"advise",en:"advise",zh:"建议",cat:"verbs",emoji:"💡"},
  {id:"encourage",en:"encourage",zh:"鼓励",cat:"verbs",emoji:"👏"},
  {id:"discourage",en:"discourage",zh:"阻止",cat:"verbs",emoji:"🚫"},
  {id:"motivate",en:"motivate",zh:"激励",cat:"verbs",emoji:"🚀"},
  {id:"inspire",en:"inspire",zh:"激励",cat:"verbs",emoji:"✨"},
  {id:"convince",en:"convince",zh:"说服",cat:"verbs",emoji:"💬"},
  {id:"persuade",en:"persuade",zh:"劝说",cat:"verbs",emoji:"💬"},
  {id:"influence",en:"influence",zh:"影响",cat:"verbs",emoji:"🌊"},
  {id:"knowledge",en:"knowledge",zh:"知识",cat:"abstract",emoji:"📚"},
  {id:"ignorance",en:"ignorance",zh:"无知",cat:"abstract",emoji:"🙈"},
  {id:"truth",en:"truth",zh:"真相",cat:"abstract",emoji:"✅"},
  {id:"lie",en:"lie",zh:"谎言",cat:"abstract",emoji:"🤥"},
  {id:"faith",en:"faith",zh:"信仰",cat:"abstract",emoji:"🙏"},
  {id:"doubt",en:"doubt",zh:"怀疑",cat:"abstract",emoji:"❓"},
  {id:"beauty",en:"beauty",zh:"美丽",cat:"abstract",emoji:"🌸"},
  {id:"ugliness",en:"ugliness",zh:"丑陋",cat:"abstract",emoji:"😬"},
  {id:"strength_abs",en:"strength",zh:"力量",cat:"abstract",emoji:"💪"},
  {id:"weakness_abs",en:"weakness",zh:"弱点",cat:"abstract",emoji:"🤕"},
  {id:"power",en:"power",zh:"权力",cat:"abstract",emoji:"⚡"},
  {id:"authority",en:"authority",zh:"权威",cat:"abstract",emoji:"👑"},
  {id:"responsibility",en:"responsibility",zh:"责任",cat:"abstract",emoji:"⚖️"},
  {id:"duty",en:"duty",zh:"职责",cat:"abstract",emoji:"📋"},
  {id:"virtue",en:"virtue",zh:"美德",cat:"abstract",emoji:"✨"},
  {id:"success",en:"success",zh:"成功",cat:"abstract",emoji:"🏆"},
  {id:"failure",en:"failure",zh:"失败",cat:"abstract",emoji:"😞"},
  {id:"progress",en:"progress",zh:"进步",cat:"abstract",emoji:"📈"},
  {id:"change",en:"change",zh:"变化",cat:"abstract",emoji:"🔄"},
  {id:"stability",en:"stability",zh:"稳定",cat:"abstract",emoji:"⚖️"},
  {id:"order",en:"order",zh:"秩序",cat:"abstract",emoji:"📋"},
  {id:"chaos",en:"chaos",zh:"混乱",cat:"abstract",emoji:"🌀"},
  {id:"unity",en:"unity",zh:"团结",cat:"abstract",emoji:"🤝"},
  {id:"division",en:"division",zh:"分裂",cat:"abstract",emoji:"✂️"},
  {id:"tradition_abs",en:"tradition",zh:"传统",cat:"abstract",emoji:"🎎"},
  {id:"innovation_abs",en:"innovation",zh:"创新",cat:"abstract",emoji:"💡"},
  {id:"identity",en:"identity",zh:"身份",cat:"abstract",emoji:"🪪"},
  {id:"communication_abs",en:"communication",zh:"沟通",cat:"abstract",emoji:"💬"},
  {id:"expression",en:"expression",zh:"表达",cat:"abstract",emoji:"🎭"},
  {id:"creativity_abs",en:"creativity",zh:"创造力",cat:"abstract",emoji:"🎨"},
  {id:"inspiration_abs",en:"inspiration",zh:"灵感",cat:"abstract",emoji:"✨"},
  {id:"motivation_abs",en:"motivation",zh:"动力",cat:"abstract",emoji:"🚀"},
  {id:"ambition",en:"ambition",zh:"抱负",cat:"abstract",emoji:"🎯"},
  {id:"aspiration",en:"aspiration",zh:"愿望",cat:"abstract",emoji:"🌟"},
  {id:"achievement",en:"achievement",zh:"成就",cat:"abstract",emoji:"🏆"},
  {id:"recognition",en:"recognition",zh:"认可",cat:"abstract",emoji:"👏"},
  {id:"reputation",en:"reputation",zh:"声誉",cat:"abstract",emoji:"⭐"},
  {id:"influence_abs",en:"influence",zh:"影响力",cat:"abstract",emoji:"🌊"},
  {id:"impact",en:"impact",zh:"影响",cat:"abstract",emoji:"💥"},
  {id:"legacy",en:"legacy",zh:"遗产",cat:"abstract",emoji:"🏛️"},
  {id:"memory_abs",en:"memory",zh:"记忆",cat:"abstract",emoji:"🧠"},
  {id:"destiny",en:"destiny",zh:"命运",cat:"abstract",emoji:"⭐"},
  {id:"purpose",en:"purpose",zh:"目的",cat:"abstract",emoji:"🎯"},
  {id:"meaning",en:"meaning",zh:"意义",cat:"abstract",emoji:"💡"},
  {id:"value",en:"value",zh:"价值",cat:"abstract",emoji:"💎"},
  {id:"belief",en:"belief",zh:"信念",cat:"abstract",emoji:"💫"},
  {id:"perspective_abs",en:"perspective",zh:"观点",cat:"abstract",emoji:"👁️"},
  {id:"attitude",en:"attitude",zh:"态度",cat:"abstract",emoji:"💭"},
  {id:"opinion",en:"opinion",zh:"意见",cat:"abstract",emoji:"💬"},
  {id:"assumption",en:"assumption",zh:"假设",cat:"abstract",emoji:"💭"},
  {id:"consequence",en:"consequence",zh:"后果",cat:"abstract",emoji:"➡️"},
  {id:"cause",en:"cause",zh:"原因",cat:"abstract",emoji:"🔍"},
  {id:"effect",en:"effect",zh:"效果",cat:"abstract",emoji:"➡️"},
  {id:"challenge",en:"challenge",zh:"挑战",cat:"abstract",emoji:"🏋️"},
  {id:"opportunity",en:"opportunity",zh:"机会",cat:"abstract",emoji:"🍀"},
  {id:"risk",en:"risk",zh:"风险",cat:"abstract",emoji:"⚠️"},
  {id:"reward",en:"reward",zh:"奖励",cat:"abstract",emoji:"🏆"},
  {id:"sacrifice",en:"sacrifice",zh:"牺牲",cat:"abstract",emoji:"💙"},
  {id:"compromise",en:"compromise",zh:"妥协",cat:"abstract",emoji:"🤝"},
  {id:"principle",en:"principle",zh:"原则",cat:"abstract",emoji:"📋"},
  {id:"concept",en:"concept",zh:"概念",cat:"abstract",emoji:"💡"},
  {id:"theory",en:"theory",zh:"理论",cat:"abstract",emoji:"📚"},
  {id:"strategy",en:"strategy",zh:"策略",cat:"abstract",emoji:"♟️"},
  {id:"priority",en:"priority",zh:"优先级",cat:"abstract",emoji:"❗"},
  {id:"potential",en:"potential",zh:"潜力",cat:"abstract",emoji:"🌱"},
  {id:"ability",en:"ability",zh:"能力",cat:"abstract",emoji:"💪"},
  {id:"skill",en:"skill",zh:"技能",cat:"abstract",emoji:"🎯"},
  {id:"talent",en:"talent",zh:"天赋",cat:"abstract",emoji:"⭐"},
  {id:"experience",en:"experience",zh:"经验",cat:"abstract",emoji:"📚"},
  {id:"judgment",en:"judgment",zh:"判断",cat:"abstract",emoji:"⚖️"},
  {id:"wisdom_abs",en:"wisdom",zh:"智慧",cat:"abstract",emoji:"🦉"},
  {id:"logic_abs",en:"logic",zh:"逻辑",cat:"abstract",emoji:"🧠"},
  {id:"pattern",en:"pattern",zh:"模式",cat:"abstract",emoji:"🔷"},
  {id:"structure",en:"structure",zh:"结构",cat:"abstract",emoji:"🏗️"},
  {id:"system",en:"system",zh:"系统",cat:"abstract",emoji:"⚙️"},
  {id:"process",en:"process",zh:"过程",cat:"abstract",emoji:"🔄"},
  {id:"method",en:"method",zh:"方法",cat:"abstract",emoji:"🛠️"},
  {id:"million",en:"million",zh:"百万",cat:"numbers",emoji:"💯"},
  {id:"billion",en:"billion",zh:"十亿",cat:"numbers",emoji:"💯"},
  {id:"half",en:"half",zh:"一半",cat:"numbers",emoji:"➗"},
  {id:"quarter",en:"quarter",zh:"四分之一",cat:"numbers",emoji:"➗"},
  {id:"percent",en:"percent",zh:"百分比",cat:"numbers",emoji:"💯"},
  {id:"ratio",en:"ratio",zh:"比例",cat:"numbers",emoji:"➗"},
  {id:"fraction",en:"fraction",zh:"分数",cat:"numbers",emoji:"➗"},
  {id:"decimal",en:"decimal",zh:"小数",cat:"numbers",emoji:"🔢"},
  {id:"average",en:"average",zh:"平均",cat:"numbers",emoji:"⚖️"},
  {id:"maximum",en:"maximum",zh:"最大",cat:"numbers",emoji:"⬆️"},
  {id:"minimum",en:"minimum",zh:"最小",cat:"numbers",emoji:"⬇️"},
  {id:"estimate_n",en:"estimate",zh:"估计",cat:"numbers",emoji:"≈"},
  {id:"calculation",en:"calculation",zh:"计算",cat:"numbers",emoji:"🧮"},
  {id:"addition",en:"addition",zh:"加法",cat:"numbers",emoji:"➕"},
  {id:"subtraction",en:"subtraction",zh:"减法",cat:"numbers",emoji:"➖"},
  {id:"multiplication",en:"multiplication",zh:"乘法",cat:"numbers",emoji:"✖️"},
  {id:"division_math",en:"division",zh:"除法",cat:"numbers",emoji:"➗"},
  {id:"thermodynamics",en:"thermodynamics",zh:"热力学",cat:"science",emoji:"🌡️"},
  {id:"quantum",en:"quantum",zh:"量子",cat:"science",emoji:"⚛️"},
  {id:"relativity",en:"relativity",zh:"相对论",cat:"science",emoji:"🌌"},
  {id:"electromagnetic",en:"electromagnetic",zh:"电磁",cat:"science",emoji:"⚡"},
  {id:"superconductor",en:"superconductor",zh:"超导体",cat:"science",emoji:"⚡"},
  {id:"semiconductor",en:"semiconductor",zh:"半导体",cat:"science",emoji:"💻"},
  {id:"nanotechnology",en:"nanotechnology",zh:"纳米技术",cat:"science",emoji:"🔬"},
  {id:"biotechnology",en:"biotechnology",zh:"生物技术",cat:"science",emoji:"🧬"},
  {id:"genetic_engineering",en:"genetic engineering",zh:"基因工程",cat:"science",emoji:"🧬"},
  {id:"stem_cell",en:"stem cell",zh:"干细胞",cat:"science",emoji:"🔬"},
  {id:"clone",en:"clone",zh:"克隆",cat:"science",emoji:"🧬"},
  {id:"mutation",en:"mutation",zh:"突变",cat:"science",emoji:"🧬"},
  {id:"natural_selection",en:"natural selection",zh:"自然选择",cat:"science",emoji:"🦕"},
  {id:"fossil",en:"fossil",zh:"化石",cat:"science",emoji:"🦕"},
  {id:"sediment",en:"sediment",zh:"沉积物",cat:"science",emoji:"🪨"},
  {id:"tectonic",en:"tectonic plates",zh:"板块构造",cat:"science",emoji:"🌍"},
  {id:"seismic",en:"seismic wave",zh:"地震波",cat:"science",emoji:"🌍"},
  {id:"magma",en:"magma",zh:"岩浆",cat:"science",emoji:"🌋"},
  {id:"lava",en:"lava",zh:"熔岩",cat:"science",emoji:"🌋"},
  {id:"mineral_rock",en:"mineral",zh:"矿物",cat:"science",emoji:"💎"},
  {id:"igneous",en:"igneous rock",zh:"火成岩",cat:"science",emoji:"🪨"},
  {id:"sedimentary",en:"sedimentary rock",zh:"沉积岩",cat:"science",emoji:"🪨"},
  {id:"metamorphic",en:"metamorphic rock",zh:"变质岩",cat:"science",emoji:"🪨"},
  {id:"erosion",en:"erosion",zh:"侵蚀",cat:"science",emoji:"💧"},
  {id:"weathering",en:"weathering",zh:"风化",cat:"science",emoji:"🌬️"},
  {id:"deposition",en:"deposition",zh:"沉积",cat:"science",emoji:"⬇️"},
  {id:"lithosphere",en:"lithosphere",zh:"岩石圈",cat:"science",emoji:"🌍"},
  {id:"atmosphere",en:"atmosphere",zh:"大气层",cat:"science",emoji:"🌤️"},
  {id:"biosphere",en:"biosphere",zh:"生物圈",cat:"science",emoji:"🌍"},
  {id:"hydrosphere",en:"hydrosphere",zh:"水圈",cat:"science",emoji:"💧"},
  {id:"evaporation",en:"evaporation",zh:"蒸发",cat:"science",emoji:"💨"},
  {id:"condensation",en:"condensation",zh:"凝结",cat:"science",emoji:"💧"},
  {id:"precipitation",en:"precipitation",zh:"降水",cat:"science",emoji:"🌧️"},
  {id:"transpiration",en:"transpiration",zh:"蒸腾",cat:"science",emoji:"🌿"},
  {id:"water_cycle",en:"water cycle",zh:"水循环",cat:"science",emoji:"♻️"},
  {id:"carbon_cycle",en:"carbon cycle",zh:"碳循环",cat:"science",emoji:"♻️"},
  {id:"nitrogen_cycle",en:"nitrogen cycle",zh:"氮循环",cat:"science",emoji:"♻️"},
  {id:"symbiosis",en:"symbiosis",zh:"共生",cat:"science",emoji:"🤝"},
  {id:"mutualism",en:"mutualism",zh:"互利共生",cat:"science",emoji:"🤝"},
  {id:"commensalism",en:"commensalism",zh:"共栖",cat:"science",emoji:"🐦"},
  {id:"parasitism",en:"parasitism",zh:"寄生",cat:"science",emoji:"🦠"},
  {id:"competition_eco",en:"competition",zh:"竞争",cat:"science",emoji:"🏆"},
  {id:"succession",en:"succession",zh:"演替",cat:"science",emoji:"🌿"},
  {id:"carrying_capacity",en:"carrying capacity",zh:"环境容纳量",cat:"science",emoji:"⚖️"},
  {id:"biomass",en:"biomass",zh:"生物量",cat:"science",emoji:"🌿"},
  {id:"trophic",en:"trophic level",zh:"营养级",cat:"science",emoji:"🔗"},
  {id:"decomposer",en:"decomposer",zh:"分解者",cat:"science",emoji:"🍄"},
  {id:"producer",en:"producer",zh:"生产者",cat:"science",emoji:"🌱"},
  {id:"consumer",en:"consumer",zh:"消费者",cat:"science",emoji:"🦁"},
  {id:"herbivore",en:"herbivore",zh:"草食动物",cat:"science",emoji:"🐰"},
  {id:"carnivore",en:"carnivore",zh:"肉食动物",cat:"science",emoji:"🦁"},
  {id:"omnivore",en:"omnivore",zh:"杂食动物",cat:"science",emoji:"🐻"},
  {id:"scavenger",en:"scavenger",zh:"食腐动物",cat:"science",emoji:"🦅"},
  {id:"decomposition",en:"decomposition",zh:"分解",cat:"science",emoji:"🍄"},
  {id:"fermentation",en:"fermentation",zh:"发酵",cat:"science",emoji:"🍶"},
  {id:"cellular_respiration",en:"cellular respiration",zh:"细胞呼吸",cat:"science",emoji:"🔬"},
  {id:"mitosis",en:"mitosis",zh:"有丝分裂",cat:"science",emoji:"🔬"},
  {id:"meiosis",en:"meiosis",zh:"减数分裂",cat:"science",emoji:"🔬"},
  {id:"genetics",en:"genetics",zh:"遗传学",cat:"science",emoji:"🧬"},
  {id:"heredity",en:"heredity",zh:"遗传",cat:"science",emoji:"🧬"},
  {id:"phenotype",en:"phenotype",zh:"表现型",cat:"science",emoji:"🧬"},
  {id:"genotype",en:"genotype",zh:"基因型",cat:"science",emoji:"🧬"},
  {id:"dominant",en:"dominant gene",zh:"显性基因",cat:"science",emoji:"🧬"},
  {id:"recessive",en:"recessive gene",zh:"隐性基因",cat:"science",emoji:"🧬"},
  {id:"allele",en:"allele",zh:"等位基因",cat:"science",emoji:"🧬"},
  {id:"trait",en:"trait",zh:"性状",cat:"science",emoji:"🧬"},
  {id:"equator",en:"equator",zh:"赤道",cat:"geography",emoji:"🌍"},
  {id:"prime_meridian",en:"prime meridian",zh:"本初子午线",cat:"geography",emoji:"🌍"},
  {id:"latitude",en:"latitude",zh:"纬度",cat:"geography",emoji:"🗺️"},
  {id:"longitude",en:"longitude",zh:"经度",cat:"geography",emoji:"🗺️"},
  {id:"tropic",en:"tropic",zh:"热带",cat:"geography",emoji:"☀️"},
  {id:"arctic_circle",en:"Arctic Circle",zh:"北极圈",cat:"geography",emoji:"🧊"},
  {id:"antarctic_circle",en:"Antarctic Circle",zh:"南极圈",cat:"geography",emoji:"🧊"},
  {id:"hemisphere",en:"hemisphere",zh:"半球",cat:"geography",emoji:"🌍"},
  {id:"time_zone",en:"time zone",zh:"时区",cat:"geography",emoji:"🕐"},
  {id:"international_date_line",en:"international date line",zh:"国际日期变更线",cat:"geography",emoji:"📅"},
  {id:"new_zealand",en:"New Zealand",zh:"新西兰",cat:"geography",emoji:"🥝"},
  {id:"switzerland",en:"Switzerland",zh:"瑞士",cat:"geography",emoji:"🏔️"},
  {id:"sweden",en:"Sweden",zh:"瑞典",cat:"geography",emoji:"🇸🇪"},
  {id:"norway",en:"Norway",zh:"挪威",cat:"geography",emoji:"🇳🇴"},
  {id:"denmark",en:"Denmark",zh:"丹麦",cat:"geography",emoji:"🇩🇰"},
  {id:"finland",en:"Finland",zh:"芬兰",cat:"geography",emoji:"🇫🇮"},
  {id:"portugal",en:"Portugal",zh:"葡萄牙",cat:"geography",emoji:"🇵🇹"},
  {id:"greece",en:"Greece",zh:"希腊",cat:"geography",emoji:"🇬🇷"},
  {id:"austria",en:"Austria",zh:"奥地利",cat:"geography",emoji:"🇦🇹"},
  {id:"belgium",en:"Belgium",zh:"比利时",cat:"geography",emoji:"🇧🇪"},
  {id:"czech_republic",en:"Czech Republic",zh:"捷克",cat:"geography",emoji:"🇨🇿"},
  {id:"hungary",en:"Hungary",zh:"匈牙利",cat:"geography",emoji:"🇭🇺"},
  {id:"romania",en:"Romania",zh:"罗马尼亚",cat:"geography",emoji:"🇷🇴"},
  {id:"morocco",en:"Morocco",zh:"摩洛哥",cat:"geography",emoji:"🇲🇦"},
  {id:"ethiopia",en:"Ethiopia",zh:"埃塞俄比亚",cat:"geography",emoji:"🇪🇹"},
  {id:"kenya",en:"Kenya",zh:"肯尼亚",cat:"geography",emoji:"🇰🇪"},
  {id:"tanzania",en:"Tanzania",zh:"坦桑尼亚",cat:"geography",emoji:"🇹🇿"},
  {id:"ghana",en:"Ghana",zh:"加纳",cat:"geography",emoji:"🇬🇭"},
  {id:"peru",en:"Peru",zh:"秘鲁",cat:"geography",emoji:"🇵🇪"},
  {id:"colombia",en:"Colombia",zh:"哥伦比亚",cat:"geography",emoji:"🇨🇴"},
  {id:"venezuela",en:"Venezuela",zh:"委内瑞拉",cat:"geography",emoji:"🇻🇪"},
  {id:"chile",en:"Chile",zh:"智利",cat:"geography",emoji:"🇨🇱"},
  {id:"iraq",en:"Iraq",zh:"伊拉克",cat:"geography",emoji:"🇮🇶"},
  {id:"iran",en:"Iran",zh:"伊朗",cat:"geography",emoji:"🇮🇷"},
  {id:"israel",en:"Israel",zh:"以色列",cat:"geography",emoji:"🇮🇱"},
  {id:"kazakhstan",en:"Kazakhstan",zh:"哈萨克斯坦",cat:"geography",emoji:"🇰🇿"},
  {id:"uzbekistan",en:"Uzbekistan",zh:"乌兹别克斯坦",cat:"geography",emoji:"🇺🇿"},
  {id:"myanmar",en:"Myanmar",zh:"缅甸",cat:"geography",emoji:"🇲🇲"},
  {id:"cambodia",en:"Cambodia",zh:"柬埔寨",cat:"geography",emoji:"🇰🇭"},
  {id:"laos",en:"Laos",zh:"老挝",cat:"geography",emoji:"🇱🇦"},
  {id:"malaysia",en:"Malaysia",zh:"马来西亚",cat:"geography",emoji:"🇲🇾"},
  {id:"singapore",en:"Singapore",zh:"新加坡",cat:"geography",emoji:"🇸🇬"},
  {id:"taiwan",en:"Taiwan",zh:"台湾",cat:"geography",emoji:"🗺️"},
  {id:"hong_kong",en:"Hong Kong",zh:"香港",cat:"geography",emoji:"🗺️"},
  {id:"tokyo_city",en:"Tokyo",zh:"东京",cat:"geography",emoji:"🏙️"},
  {id:"mumbai",en:"Mumbai",zh:"孟买",cat:"geography",emoji:"🏙️"},
  {id:"cairo_city",en:"Cairo",zh:"开罗",cat:"geography",emoji:"🏙️"},
  {id:"istanbul",en:"Istanbul",zh:"伊斯坦布尔",cat:"geography",emoji:"🏙️"},
  {id:"amsterdam",en:"Amsterdam",zh:"阿姆斯特丹",cat:"geography",emoji:"🏙️"},
  {id:"barcelona",en:"Barcelona",zh:"巴塞罗那",cat:"geography",emoji:"🏙️"},
  {id:"vienna",en:"Vienna",zh:"维也纳",cat:"geography",emoji:"🏙️"},
  {id:"stockholm",en:"Stockholm",zh:"斯德哥尔摩",cat:"geography",emoji:"🏙️"},
  {id:"oslo",en:"Oslo",zh:"奥斯陆",cat:"geography",emoji:"🏙️"},
  {id:"copenhagen",en:"Copenhagen",zh:"哥本哈根",cat:"geography",emoji:"🏙️"},
  {id:"ancient_egypt",en:"ancient Egypt",zh:"古埃及",cat:"history",emoji:"🏺"},
  {id:"ancient_greece",en:"ancient Greece",zh:"古希腊",cat:"history",emoji:"🏛️"},
  {id:"ancient_rome",en:"ancient Rome",zh:"古罗马",cat:"history",emoji:"🏛️"},
  {id:"ancient_china",en:"ancient China",zh:"古中国",cat:"history",emoji:"🏯"},
  {id:"mesopotamia",en:"Mesopotamia",zh:"美索不达米亚",cat:"history",emoji:"🏺"},
  {id:"maya",en:"Maya civilization",zh:"玛雅文明",cat:"history",emoji:"🏛️"},
  {id:"inca",en:"Inca civilization",zh:"印加文明",cat:"history",emoji:"🏔️"},
  {id:"aztec",en:"Aztec civilization",zh:"阿兹特克文明",cat:"history",emoji:"🌽"},
  {id:"roman_empire",en:"Roman Empire",zh:"罗马帝国",cat:"history",emoji:"🏛️"},
  {id:"ottoman_empire",en:"Ottoman Empire",zh:"奥斯曼帝国",cat:"history",emoji:"🕌"},
  {id:"mongol_empire",en:"Mongol Empire",zh:"蒙古帝国",cat:"history",emoji:"🏇"},
  {id:"british_empire",en:"British Empire",zh:"大英帝国",cat:"history",emoji:"👑"},
  {id:"world_war_1",en:"World War I",zh:"第一次世界大战",cat:"history",emoji:"⚔️"},
  {id:"world_war_2",en:"World War II",zh:"第二次世界大战",cat:"history",emoji:"⚔️"},
  {id:"cold_war",en:"Cold War",zh:"冷战",cat:"history",emoji:"❄️"},
  {id:"french_revolution",en:"French Revolution",zh:"法国大革命",cat:"history",emoji:"🇫🇷"},
  {id:"american_revolution",en:"American Revolution",zh:"美国独立战争",cat:"history",emoji:"🇺🇸"},
  {id:"chinese_revolution",en:"Chinese Revolution",zh:"中国革命",cat:"history",emoji:"🇨🇳"},
  {id:"civil_rights",en:"civil rights movement",zh:"民权运动",cat:"history",emoji:"✊"},
  {id:"feminist_movement",en:"feminist movement",zh:"女权运动",cat:"history",emoji:"♀️"},
  {id:"enlightenment_hist",en:"Enlightenment",zh:"启蒙时代",cat:"history",emoji:"💡"},
  {id:"colonization",en:"colonization",zh:"殖民化",cat:"history",emoji:"⛵"},
  {id:"decolonization",en:"decolonization",zh:"去殖民化",cat:"history",emoji:"🕊️"},
  {id:"apartheid",en:"apartheid",zh:"种族隔离",cat:"history",emoji:"✊"},
  {id:"genocide",en:"genocide",zh:"种族灭绝",cat:"history",emoji:"⚠️"},
  {id:"holocaust",en:"Holocaust",zh:"大屠杀",cat:"history",emoji:"⚠️"},
  {id:"hiroshima",en:"Hiroshima",zh:"广岛",cat:"history",emoji:"🕊️"},
  {id:"berlin_wall",en:"Berlin Wall",zh:"柏林墙",cat:"history",emoji:"🧱"},
  {id:"moon_landing",en:"moon landing",zh:"登月",cat:"history",emoji:"🌙"},
  {id:"industrial_age",en:"industrial age",zh:"工业时代",cat:"history",emoji:"🏭"},
  {id:"psychology",en:"psychology",zh:"心理学",cat:"science",emoji:"🧠"},
  {id:"behavior",en:"behavior",zh:"行为",cat:"science",emoji:"🧍"},
  {id:"personality",en:"personality",zh:"个性",cat:"science",emoji:"💁"},
  {id:"temperament",en:"temperament",zh:"气质",cat:"science",emoji:"💁"},
  {id:"intelligence",en:"intelligence",zh:"智力",cat:"science",emoji:"🧠"},
  {id:"creativity",en:"creativity",zh:"创造力",cat:"science",emoji:"🎨"},
  {id:"perception",en:"perception",zh:"感知",cat:"science",emoji:"👁️"},
  {id:"cognition",en:"cognition",zh:"认知",cat:"science",emoji:"🧠"},
  {id:"memory",en:"memory",zh:"记忆力",cat:"science",emoji:"🧠"},
  {id:"attention",en:"attention",zh:"注意力",cat:"science",emoji:"👁️"},
  {id:"emotion",en:"emotion",zh:"情绪",cat:"science",emoji:"❤️"},
  {id:"motivation",en:"motivation",zh:"动机",cat:"science",emoji:"🚀"},
  {id:"habit",en:"habit",zh:"习惯",cat:"science",emoji:"🔄"},
  {id:"instinct",en:"instinct",zh:"本能",cat:"science",emoji:"🦁"},
  {id:"reflex",en:"reflex",zh:"反射",cat:"science",emoji:"⚡"},
  {id:"consciousness",en:"consciousness",zh:"意识",cat:"science",emoji:"🧠"},
  {id:"unconscious",en:"unconscious",zh:"无意识",cat:"science",emoji:"💤"},
  {id:"subconscious",en:"subconscious",zh:"潜意识",cat:"science",emoji:"💭"},
  {id:"empathy",en:"empathy",zh:"同理心",cat:"science",emoji:"❤️"},
  {id:"compassion",en:"compassion",zh:"慈悲",cat:"science",emoji:"💙"},
  {id:"resilience",en:"resilience",zh:"韧性",cat:"science",emoji:"💪"},
  {id:"self_esteem",en:"self-esteem",zh:"自尊",cat:"science",emoji:"💪"},
  {id:"anxiety_psych",en:"anxiety",zh:"焦虑",cat:"science",emoji:"😰"},
  {id:"depression",en:"depression",zh:"抑郁",cat:"science",emoji:"😞"},
  {id:"stress",en:"stress",zh:"压力",cat:"science",emoji:"😓"},
  {id:"trauma",en:"trauma",zh:"创伤",cat:"science",emoji:"💔"},
  {id:"therapy_psych",en:"therapy",zh:"心理治疗",cat:"science",emoji:"🛋️"},
  {id:"counseling",en:"counseling",zh:"咨询",cat:"science",emoji:"💬"},
  {id:"artificial_intelligence",en:"artificial intelligence",zh:"人工智能",cat:"technology",emoji:"🤖"},
  {id:"machine_learning",en:"machine learning",zh:"机器学习",cat:"technology",emoji:"💻"},
  {id:"algorithm",en:"algorithm",zh:"算法",cat:"technology",emoji:"💻"},
  {id:"database",en:"database",zh:"数据库",cat:"technology",emoji:"🗄️"},
  {id:"programming",en:"programming",zh:"编程",cat:"technology",emoji:"💻"},
  {id:"coding",en:"coding",zh:"编码",cat:"technology",emoji:"💻"},
  {id:"debugging",en:"debugging",zh:"调试",cat:"technology",emoji:"🐛"},
  {id:"software",en:"software",zh:"软件",cat:"technology",emoji:"💻"},
  {id:"hardware",en:"hardware",zh:"硬件",cat:"technology",emoji:"💻"},
  {id:"operating_system",en:"operating system",zh:"操作系统",cat:"technology",emoji:"💻"},
  {id:"browser",en:"browser",zh:"浏览器",cat:"technology",emoji:"🌐"},
  {id:"email",en:"email",zh:"电子邮件",cat:"technology",emoji:"📧"},
  {id:"password",en:"password",zh:"密码",cat:"technology",emoji:"🔑"},
  {id:"encryption",en:"encryption",zh:"加密",cat:"technology",emoji:"🔒"},
  {id:"cybersecurity",en:"cybersecurity",zh:"网络安全",cat:"technology",emoji:"🛡️"},
  {id:"hacker",en:"hacker",zh:"黑客",cat:"technology",emoji:"💻"},
  {id:"network",en:"network",zh:"网络",cat:"technology",emoji:"🌐"},
  {id:"server",en:"server",zh:"服务器",cat:"technology",emoji:"🖥️"},
  {id:"cloud_computing",en:"cloud computing",zh:"云计算",cat:"technology",emoji:"☁️"},
  {id:"social_media",en:"social media",zh:"社交媒体",cat:"technology",emoji:"📱"},
  {id:"virtual_reality",en:"virtual reality",zh:"虚拟现实",cat:"technology",emoji:"🥽"},
  {id:"augmented_reality",en:"augmented reality",zh:"增强现实",cat:"technology",emoji:"🥽"},
  {id:"blockchain",en:"blockchain",zh:"区块链",cat:"technology",emoji:"🔗"},
  {id:"cryptocurrency",en:"cryptocurrency",zh:"加密货币",cat:"technology",emoji:"₿"},
  {id:"3d_printing",en:"3D printing",zh:"三维打印",cat:"technology",emoji:"🖨️"},
  {id:"autonomous",en:"autonomous vehicle",zh:"自动驾驶",cat:"technology",emoji:"🚗"},
  {id:"space_station",en:"space station",zh:"空间站",cat:"technology",emoji:"🛸"},
  {id:"rocket_tech",en:"rocket",zh:"火箭",cat:"technology",emoji:"🚀"},
  {id:"gps",en:"GPS",zh:"全球定位系统",cat:"technology",emoji:"📍"},
  {id:"fiber_optic",en:"fiber optic",zh:"光纤",cat:"technology",emoji:"💡"},
  {id:"impressionist",en:"Impressionist",zh:"印象派",cat:"arts",emoji:"🎨"},
  {id:"surrealism",en:"surrealism",zh:"超现实主义",cat:"arts",emoji:"🎨"},
  {id:"expressionism",en:"expressionism",zh:"表现主义",cat:"arts",emoji:"🎨"},
  {id:"minimalism",en:"minimalism",zh:"简约主义",cat:"arts",emoji:"⬛"},
  {id:"pop_art",en:"pop art",zh:"流行艺术",cat:"arts",emoji:"🎨"},
  {id:"street_art",en:"street art",zh:"街头艺术",cat:"arts",emoji:"🖌️"},
  {id:"installation",en:"installation art",zh:"装置艺术",cat:"arts",emoji:"🎭"},
  {id:"performance_art",en:"performance art",zh:"表演艺术",cat:"arts",emoji:"🎭"},
  {id:"cinema_art",en:"cinema",zh:"电影艺术",cat:"arts",emoji:"🎬"},
  {id:"documentary",en:"documentary",zh:"纪录片",cat:"arts",emoji:"🎬"},
  {id:"animation",en:"animation",zh:"动画",cat:"arts",emoji:"🎬"},
  {id:"comic",en:"comic",zh:"漫画",cat:"arts",emoji:"📚"},
  {id:"manga",en:"manga",zh:"漫画",cat:"arts",emoji:"📚"},
  {id:"graphic_novel",en:"graphic novel",zh:"图像小说",cat:"arts",emoji:"📚"},
  {id:"screenplay",en:"screenplay",zh:"剧本",cat:"arts",emoji:"📝"},
  {id:"libretto",en:"libretto",zh:"歌剧剧本",cat:"arts",emoji:"📝"},
  {id:"choreography",en:"choreography",zh:"编舞",cat:"arts",emoji:"🩰"},
  {id:"improvisation",en:"improvisation",zh:"即兴创作",cat:"arts",emoji:"🎭"},
  {id:"rehearsal",en:"rehearsal",zh:"排练",cat:"arts",emoji:"🎭"},
  {id:"premiere",en:"premiere",zh:"首映",cat:"arts",emoji:"🎬"},
  {id:"intermission",en:"intermission",zh:"中场休息",cat:"arts",emoji:"🎭"},
  {id:"critique",en:"critique",zh:"评论",cat:"arts",emoji:"📝"},
  {id:"aesthetic",en:"aesthetic",zh:"美学",cat:"arts",emoji:"🎨"},
  {id:"motif",en:"motif",zh:"主题",cat:"arts",emoji:"🔷"},
  {id:"hypothesis_acad",en:"hypothesis",zh:"假说",cat:"academic",emoji:"💡"},
  {id:"methodology",en:"methodology",zh:"方法论",cat:"academic",emoji:"📋"},
  {id:"peer_review",en:"peer review",zh:"同行评审",cat:"academic",emoji:"🔍"},
  {id:"abstract_acad",en:"abstract",zh:"摘要",cat:"academic",emoji:"📝"},
  {id:"introduction",en:"introduction",zh:"引言",cat:"academic",emoji:"📝"},
  {id:"methodology_acad",en:"methodology",zh:"研究方法",cat:"academic",emoji:"📋"},
  {id:"discussion",en:"discussion",zh:"讨论",cat:"academic",emoji:"💬"},
  {id:"appendix",en:"appendix",zh:"附录",cat:"academic",emoji:"📚"},
  {id:"footnote",en:"footnote",zh:"脚注",cat:"academic",emoji:"📝"},
  {id:"index",en:"index",zh:"索引",cat:"academic",emoji:"📚"},
  {id:"glossary",en:"glossary",zh:"词汇表",cat:"academic",emoji:"📚"},
  {id:"anthology",en:"anthology",zh:"选集",cat:"academic",emoji:"📚"},
  {id:"paraphrase",en:"paraphrase",zh:"释义",cat:"academic",emoji:"📝"},
  {id:"annotation",en:"annotation",zh:"注释",cat:"academic",emoji:"📝"},
  {id:"critique_acad",en:"critique",zh:"批评",cat:"academic",emoji:"📝"},
  {id:"synthesis",en:"synthesis",zh:"综合",cat:"academic",emoji:"🔬"},
  {id:"deduction",en:"deduction",zh:"演绎",cat:"academic",emoji:"🧠"},
  {id:"induction",en:"induction",zh:"归纳",cat:"academic",emoji:"🧠"},
  {id:"paradigm",en:"paradigm",zh:"范式",cat:"academic",emoji:"🔄"},
  {id:"epistemology",en:"epistemology",zh:"认识论",cat:"academic",emoji:"🧠"},
  {id:"morality",en:"morality",zh:"道德",cat:"abstract",emoji:"⚖️"},
  {id:"ethics",en:"ethics",zh:"伦理",cat:"abstract",emoji:"⚖️"},
  {id:"integrity",en:"integrity",zh:"诚信",cat:"abstract",emoji:"🤝"},
  {id:"loyalty",en:"loyalty",zh:"忠诚",cat:"abstract",emoji:"💙"},
  {id:"honor",en:"honor",zh:"荣誉",cat:"abstract",emoji:"🏆"},
  {id:"dignity",en:"dignity",zh:"尊严",cat:"abstract",emoji:"👑"},
  {id:"humility",en:"humility",zh:"谦逊",cat:"abstract",emoji:"🙏"},
  {id:"empathy_abs",en:"empathy",zh:"同情心",cat:"abstract",emoji:"❤️"},
  {id:"compassion_abs",en:"compassion",zh:"慈悲",cat:"abstract",emoji:"💙"},
  {id:"tolerance",en:"tolerance",zh:"宽容",cat:"abstract",emoji:"🤲"},
  {id:"acceptance",en:"acceptance",zh:"接受",cat:"abstract",emoji:"✅"},
  {id:"inclusion",en:"inclusion",zh:"包容",cat:"abstract",emoji:"🤝"},
  {id:"diversity",en:"diversity",zh:"多样性",cat:"abstract",emoji:"🌈"},
  {id:"discrimination",en:"discrimination",zh:"歧视",cat:"abstract",emoji:"⚠️"},
  {id:"prejudice",en:"prejudice",zh:"偏见",cat:"abstract",emoji:"⚠️"},
  {id:"stereotype",en:"stereotype",zh:"刻板印象",cat:"abstract",emoji:"🏷️"},
  {id:"bias",en:"bias",zh:"偏见",cat:"abstract",emoji:"⚖️"},
  {id:"privilege",en:"privilege",zh:"特权",cat:"abstract",emoji:"👑"},
  {id:"oppression",en:"oppression",zh:"压迫",cat:"abstract",emoji:"⛓️"},
  {id:"resistance",en:"resistance",zh:"抵抗",cat:"abstract",emoji:"✊"},
  {id:"solidarity",en:"solidarity",zh:"团结",cat:"abstract",emoji:"🤝"},
  {id:"accountability",en:"accountability",zh:"问责",cat:"abstract",emoji:"⚖️"},
  {id:"transparency_abs",en:"transparency",zh:"透明度",cat:"abstract",emoji:"🪟"},
  {id:"authenticity",en:"authenticity",zh:"真实性",cat:"abstract",emoji:"✅"},
  {id:"vulnerability_abs",en:"vulnerability",zh:"脆弱性",cat:"abstract",emoji:"💔"},
  {id:"resilience_abs",en:"resilience",zh:"韧性",cat:"abstract",emoji:"💪"},
  {id:"perseverance",en:"perseverance",zh:"坚持",cat:"abstract",emoji:"💪"},
  {id:"determination",en:"determination",zh:"决心",cat:"abstract",emoji:"💪"},
  {id:"dedication",en:"dedication",zh:"奉献",cat:"abstract",emoji:"❤️"},
  {id:"passion",en:"passion",zh:"激情",cat:"abstract",emoji:"🔥"},
  {id:"curiosity",en:"curiosity",zh:"好奇心",cat:"abstract",emoji:"🔍"},
  {id:"enthusiasm_abs",en:"enthusiasm",zh:"热情",cat:"abstract",emoji:"🤩"},
  {id:"wonder",en:"wonder",zh:"惊奇",cat:"abstract",emoji:"✨"},
  {id:"awe",en:"awe",zh:"敬畏",cat:"abstract",emoji:"😮"},
  {id:"gratitude",en:"gratitude",zh:"感恩",cat:"abstract",emoji:"🙏"},
  {id:"forgiveness",en:"forgiveness",zh:"宽恕",cat:"abstract",emoji:"🕊️"},
  {id:"reconciliation",en:"reconciliation",zh:"和解",cat:"abstract",emoji:"🤝"},
  {id:"empowerment",en:"empowerment",zh:"赋权",cat:"abstract",emoji:"💪"},
  {id:"liberation",en:"liberation",zh:"解放",cat:"abstract",emoji:"🕊️"},
  {id:"oppression_abs",en:"oppression",zh:"压迫",cat:"abstract",emoji:"⛓️"},
  {id:"ambivalent",en:"ambivalent",zh:"矛盾",cat:"adjectives",emoji:"🔀"},
  {id:"ambiguous_adj",en:"ambiguous",zh:"模糊",cat:"adjectives",emoji:"❓"},
  {id:"nuanced",en:"nuanced",zh:"微妙",cat:"adjectives",emoji:"🔍"},
  {id:"paradoxical",en:"paradoxical",zh:"矛盾",cat:"adjectives",emoji:"🔀"},
  {id:"intricate",en:"intricate",zh:"复杂精细",cat:"adjectives",emoji:"🔬"},
  {id:"elaborate",en:"elaborate",zh:"精心设计",cat:"adjectives",emoji:"🎨"},
  {id:"meticulous",en:"meticulous",zh:"一丝不苟",cat:"adjectives",emoji:"🔍"},
  {id:"systematic",en:"systematic",zh:"系统化",cat:"adjectives",emoji:"⚙️"},
  {id:"methodical",en:"methodical",zh:"有条理",cat:"adjectives",emoji:"📋"},
  {id:"spontaneous",en:"spontaneous",zh:"自发",cat:"adjectives",emoji:"⚡"},
  {id:"deliberate",en:"deliberate",zh:"蓄意",cat:"adjectives",emoji:"🎯"},
  {id:"impulsive",en:"impulsive",zh:"冲动",cat:"adjectives",emoji:"⚡"},
  {id:"persistent",en:"persistent",zh:"坚持不懈",cat:"adjectives",emoji:"💪"},
  {id:"tenacious",en:"tenacious",zh:"顽强",cat:"adjectives",emoji:"💪"},
  {id:"ambitious_adj",en:"ambitious",zh:"有抱负",cat:"adjectives",emoji:"🎯"},
  {id:"versatile",en:"versatile",zh:"多才多艺",cat:"adjectives",emoji:"🔄"},
  {id:"resourceful",en:"resourceful",zh:"足智多谋",cat:"adjectives",emoji:"💡"},
  {id:"innovative_adj",en:"innovative",zh:"创新",cat:"adjectives",emoji:"💡"},
  {id:"pragmatic",en:"pragmatic",zh:"务实",cat:"adjectives",emoji:"🔧"},
  {id:"idealistic",en:"idealistic",zh:"理想主义",cat:"adjectives",emoji:"🌟"},
  {id:"skeptical",en:"skeptical",zh:"怀疑",cat:"adjectives",emoji:"❓"},
  {id:"critical",en:"critical",zh:"批判性",cat:"adjectives",emoji:"🔍"},
  {id:"neutral",en:"neutral",zh:"中立",cat:"adjectives",emoji:"⚖️"},
  {id:"impartial",en:"impartial",zh:"公正",cat:"adjectives",emoji:"⚖️"},
  {id:"biased",en:"biased",zh:"有偏见",cat:"adjectives",emoji:"⚖️"},
  {id:"empathetic",en:"empathetic",zh:"有同理心",cat:"adjectives",emoji:"❤️"},
  {id:"articulate",en:"articulate",zh:"清晰表达",cat:"verbs",emoji:"💬"},
  {id:"elaborate_v",en:"elaborate",zh:"详细说明",cat:"verbs",emoji:"📋"},
  {id:"clarify",en:"clarify",zh:"澄清",cat:"verbs",emoji:"💡"},
  {id:"justify",en:"justify",zh:"证明",cat:"verbs",emoji:"⚖️"},
  {id:"validate",en:"validate",zh:"验证",cat:"verbs",emoji:"✅"},
  {id:"contradict",en:"contradict",zh:"矛盾",cat:"verbs",emoji:"❌"},
  {id:"acknowledge",en:"acknowledge",zh:"承认",cat:"verbs",emoji:"✅"},
  {id:"anticipate",en:"anticipate",zh:"预期",cat:"verbs",emoji:"🔮"},
  {id:"perceive",en:"perceive",zh:"感知",cat:"verbs",emoji:"👁️"},
  {id:"conceive",en:"conceive",zh:"构想",cat:"verbs",emoji:"💭"},
  {id:"formulate",en:"formulate",zh:"制定",cat:"verbs",emoji:"📋"},
  {id:"hypothesize",en:"hypothesize",zh:"假设",cat:"verbs",emoji:"💡"},
  {id:"theorize",en:"theorize",zh:"理论化",cat:"verbs",emoji:"📚"},
  {id:"generalize",en:"generalize",zh:"概括",cat:"verbs",emoji:"📊"},
  {id:"specialize",en:"specialize",zh:"专业化",cat:"verbs",emoji:"🎯"},
  {id:"integrate",en:"integrate",zh:"整合",cat:"verbs",emoji:"🔗"},
  {id:"differentiate",en:"differentiate",zh:"区分",cat:"verbs",emoji:"🔀"},
  {id:"synthesize",en:"synthesize",zh:"综合",cat:"verbs",emoji:"🔬"},
  {id:"rationalize",en:"rationalize",zh:"合理化",cat:"verbs",emoji:"🧠"},
  {id:"prioritize",en:"prioritize",zh:"优先考虑",cat:"verbs",emoji:"❗"},
  {id:"optimize",en:"optimize",zh:"优化",cat:"verbs",emoji:"📈"},
  {id:"delegate",en:"delegate",zh:"委派",cat:"verbs",emoji:"👤"},
  {id:"facilitate",en:"facilitate",zh:"促进",cat:"verbs",emoji:"🤝"},
  {id:"mediate",en:"mediate",zh:"调解",cat:"verbs",emoji:"🤝"},
  {id:"arbitrate",en:"arbitrate",zh:"仲裁",cat:"verbs",emoji:"⚖️"},
  {id:"negotiate_deal",en:"negotiate",zh:"谈判",cat:"verbs",emoji:"🤝"},
  {id:"compromise_v",en:"compromise",zh:"妥协",cat:"verbs",emoji:"🤝"},
  {id:"collaborate_v",en:"collaborate",zh:"合作",cat:"verbs",emoji:"🤝"},
  {id:"innovate",en:"innovate",zh:"创新",cat:"verbs",emoji:"💡"},
  {id:"revolutionize",en:"revolutionize",zh:"革命化",cat:"verbs",emoji:"🔄"},
  {id:"transform_v",en:"transform",zh:"改变",cat:"verbs",emoji:"🔄"},
  {id:"evolve",en:"evolve",zh:"进化",cat:"verbs",emoji:"🦕"},
  {id:"adapt",en:"adapt",zh:"适应",cat:"verbs",emoji:"🔄"},
  {id:"sustain",en:"sustain",zh:"维持",cat:"verbs",emoji:"♻️"},
  {id:"preserve",en:"preserve",zh:"保存",cat:"verbs",emoji:"📦"},
  {id:"restore",en:"restore",zh:"恢复",cat:"verbs",emoji:"🔄"},
  {id:"rehabilitate",en:"rehabilitate",zh:"康复",cat:"verbs",emoji:"🏥"},
  {id:"reconstruct",en:"reconstruct",zh:"重建",cat:"verbs",emoji:"🏗️"},
  {id:"reinterpret",en:"reinterpret",zh:"重新解释",cat:"verbs",emoji:"🔄"},
  {id:"reconsider",en:"reconsider",zh:"重新考虑",cat:"verbs",emoji:"💭"}
];
