const WORDS_BASE = [
  // Animals
  {id:"dog",    emoji:"🐕", en:"dog",      zh:"狗",    cat:"animals", def_en:"A friendly animal that barks",         def_zh:"一种会叫的友好动物"},
  {id:"cat",    emoji:"🐈", en:"cat",      zh:"猫",    cat:"animals", def_en:"A soft furry animal that purrs",       def_zh:"一种毛茸茸会咕噜叫的动物"},
  {id:"bird",   emoji:"🐦", en:"bird",     zh:"鸟",    cat:"animals", def_en:"An animal with wings that can fly",    def_zh:"一种有翅膀会飞的动物"},
  {id:"fish",   emoji:"🐟", en:"fish",     zh:"鱼",    cat:"animals", def_en:"An animal that lives in water",        def_zh:"一种生活在水里的动物"},
  {id:"rabbit", emoji:"🐰", en:"rabbit",   zh:"兔子",  cat:"animals", def_en:"A fluffy animal with long ears",       def_zh:"一种耳朵长的毛茸茸动物"},
  {id:"elephant",emoji:"🐘",en:"elephant", zh:"大象",  cat:"animals", def_en:"The biggest land animal with a trunk", def_zh:"陆地上最大的动物，有长鼻子"},
  {id:"lion",   emoji:"🦁", en:"lion",     zh:"狮子",  cat:"animals", def_en:"A big cat called the king of jungle",  def_zh:"被称为丛林之王的大猫"},
  {id:"monkey", emoji:"🐒", en:"monkey",   zh:"猴子",  cat:"animals", def_en:"A clever animal that climbs trees",    def_zh:"一种聪明的会爬树的动物"},
  {id:"duck",   emoji:"🦆", en:"duck",     zh:"鸭子",  cat:"animals", def_en:"A bird that swims and says quack",     def_zh:"一种会游泳叫嘎嘎的鸟"},
  {id:"horse",  emoji:"🐴", en:"horse",    zh:"马",    cat:"animals", def_en:"A large animal people ride",           def_zh:"一种人类骑的大动物"},
  {id:"cow",    emoji:"🐄", en:"cow",      zh:"奶牛",  cat:"animals", def_en:"A farm animal that gives us milk",     def_zh:"一种给我们牛奶的农场动物"},
  {id:"frog",   emoji:"🐸", en:"frog",     zh:"青蛙",  cat:"animals", def_en:"A green animal that jumps and croaks", def_zh:"一种绿色会跳会呱呱叫的动物"},
  // Food
  {id:"apple",  emoji:"🍎", en:"apple",    zh:"苹果",  cat:"food", def_en:"A round red or green fruit",            def_zh:"一种圆形的红色或绿色水果"},
  {id:"banana", emoji:"🍌", en:"banana",   zh:"香蕉",  cat:"food", def_en:"A long yellow fruit monkeys love",      def_zh:"猴子喜欢吃的黄色长形水果"},
  {id:"rice",   emoji:"🍚", en:"rice",     zh:"米饭",  cat:"food", def_en:"Small white grains we eat with meals",  def_zh:"我们吃饭时吃的白色小粒食物"},
  {id:"bread",  emoji:"🍞", en:"bread",    zh:"面包",  cat:"food", def_en:"A soft food we make sandwiches with",   def_zh:"我们用来做三明治的软食物"},
  {id:"milk",   emoji:"🥛", en:"milk",     zh:"牛奶",  cat:"food", def_en:"A white drink that makes bones strong", def_zh:"能让骨骼强壮的白色饮料"},
  {id:"egg",    emoji:"🥚", en:"egg",      zh:"鸡蛋",  cat:"food", def_en:"A food that comes from a chicken",      def_zh:"从鸡身上来的食物"},
  {id:"orange", emoji:"🍊", en:"orange",   zh:"橙子",  cat:"food", def_en:"A round juicy fruit with orange skin",  def_zh:"一种皮是橙色的多汁水果"},
  {id:"cake",   emoji:"🎂", en:"cake",     zh:"蛋糕",  cat:"food", def_en:"A sweet dessert for birthdays",         def_zh:"生日时吃的甜点"},
  {id:"carrot", emoji:"🥕", en:"carrot",   zh:"胡萝卜",cat:"food", def_en:"An orange vegetable rabbits love",      def_zh:"兔子喜欢吃的橙色蔬菜"},
  {id:"noodles",emoji:"🍜", en:"noodles",  zh:"面条",  cat:"food", def_en:"Long thin food made from flour",        def_zh:"用面粉做的又长又细的食物"},
  // Colours
  {id:"red",    emoji:"🔴", en:"red",      zh:"红色",  cat:"colours", def_en:"The colour of apples and fire trucks",  def_zh:"苹果和消防车的颜色"},
  {id:"blue",   emoji:"🔵", en:"blue",     zh:"蓝色",  cat:"colours", def_en:"The colour of the sky and the sea",     def_zh:"天空和大海的颜色"},
  {id:"green",  emoji:"🟢", en:"green",    zh:"绿色",  cat:"colours", def_en:"The colour of grass and leaves",        def_zh:"草地和树叶的颜色"},
  {id:"yellow", emoji:"🟡", en:"yellow",   zh:"黄色",  cat:"colours", def_en:"The colour of bananas and the sun",     def_zh:"香蕉和太阳的颜色"},
  {id:"pink",   emoji:"🌸", en:"pink",     zh:"粉色",  cat:"colours", def_en:"A light red colour like flowers",       def_zh:"像花朵一样的淡红色"},
  {id:"purple", emoji:"🟣", en:"purple",   zh:"紫色",  cat:"colours", def_en:"A mix of red and blue colour",          def_zh:"红色和蓝色混合的颜色"},
  {id:"white",  emoji:"⬜", en:"white",    zh:"白色",  cat:"colours", def_en:"The colour of snow and clouds",         def_zh:"雪和云的颜色"},
  {id:"black",  emoji:"⬛", en:"black",    zh:"黑色",  cat:"colours", def_en:"The darkest colour like night",         def_zh:"像夜晚一样最深的颜色"},
  // Body parts
  {id:"eye",    emoji:"👁",  en:"eye",      zh:"眼睛",  cat:"body", def_en:"You use these to see things",           def_zh:"你用来看东西的器官"},
  {id:"ear",    emoji:"👂",  en:"ear",      zh:"耳朵",  cat:"body", def_en:"You use these to hear sounds",          def_zh:"你用来听声音的器官"},
  {id:"nose",   emoji:"👃",  en:"nose",     zh:"鼻子",  cat:"body", def_en:"You use this to smell things",          def_zh:"你用来闻气味的器官"},
  {id:"mouth",  emoji:"👄",  en:"mouth",    zh:"嘴巴",  cat:"body", def_en:"You use this to eat and talk",          def_zh:"你用来吃东西和说话的器官"},
  {id:"hand",   emoji:"✋",  en:"hand",     zh:"手",    cat:"body", def_en:"You use these to hold and wave hello",  def_zh:"你用来握东西和打招呼的器官"},
  {id:"foot",   emoji:"🦶",  en:"foot",     zh:"脚",    cat:"body", def_en:"You use these to walk and run",         def_zh:"你用来走路和跑步的器官"},
  {id:"head",   emoji:"🗣",  en:"head",     zh:"头",    cat:"body", def_en:"The top part of your body",             def_zh:"你身体最上面的部分"},
  {id:"heart",  emoji:"❤️", en:"heart",    zh:"心脏",  cat:"body", def_en:"The organ that pumps blood inside you", def_zh:"在你体内泵送血液的器官"},
  // Numbers
  {id:"one",    emoji:"1️⃣", en:"one",      zh:"一",    cat:"numbers", def_en:"The number 1",  def_zh:"数字1"},
  {id:"two",    emoji:"2️⃣", en:"two",      zh:"二",    cat:"numbers", def_en:"The number 2",  def_zh:"数字2"},
  {id:"three",  emoji:"3️⃣", en:"three",    zh:"三",    cat:"numbers", def_en:"The number 3",  def_zh:"数字3"},
  {id:"four",   emoji:"4️⃣", en:"four",     zh:"四",    cat:"numbers", def_en:"The number 4",  def_zh:"数字4"},
  {id:"five",   emoji:"5️⃣", en:"five",     zh:"五",    cat:"numbers", def_en:"The number 5",  def_zh:"数字5"},
  {id:"six",    emoji:"6️⃣", en:"six",      zh:"六",    cat:"numbers", def_en:"The number 6",  def_zh:"数字6"},
  {id:"seven",  emoji:"7️⃣", en:"seven",    zh:"七",    cat:"numbers", def_en:"The number 7",  def_zh:"数字7"},
  {id:"eight",  emoji:"8️⃣", en:"eight",    zh:"八",    cat:"numbers", def_en:"The number 8",  def_zh:"数字8"},
  {id:"nine",   emoji:"9️⃣", en:"nine",     zh:"九",    cat:"numbers", def_en:"The number 9",  def_zh:"数字9"},
  {id:"ten",    emoji:"🔟",  en:"ten",      zh:"十",    cat:"numbers", def_en:"The number 10", def_zh:"数字10"},
  // Family
  {id:"mother", emoji:"👩", en:"mother",   zh:"妈妈",  cat:"family", def_en:"The woman who takes care of you",       def_zh:"照顾你的女士"},
  {id:"father", emoji:"👨", en:"father",   zh:"爸爸",  cat:"family", def_en:"The man who takes care of you",         def_zh:"照顾你的男士"},
  {id:"baby",   emoji:"👶", en:"baby",     zh:"宝宝",  cat:"family", def_en:"A very young child who needs help",     def_zh:"需要帮助的很小的孩子"},
  {id:"sister", emoji:"👧", en:"sister",   zh:"姐妹",  cat:"family", def_en:"A girl who has the same parents as you",def_zh:"和你父母相同的女孩"},
  {id:"brother",emoji:"👦", en:"brother",  zh:"兄弟",  cat:"family", def_en:"A boy who has the same parents as you", def_zh:"和你父母相同的男孩"},
  {id:"grandma",emoji:"👵", en:"grandma",  zh:"奶奶",  cat:"family", def_en:"Your mum's or dad's mother",            def_zh:"你爸爸或妈妈的妈妈"},
  {id:"grandpa",emoji:"👴", en:"grandpa",  zh:"爷爷",  cat:"family", def_en:"Your mum's or dad's father",            def_zh:"你爸爸或妈妈的爸爸"},
  // Clothes
  {id:"shirt",  emoji:"👕", en:"shirt",    zh:"衬衫",  cat:"clothes", def_en:"A top you wear on your upper body",     def_zh:"穿在上半身的衣服"},
  {id:"pants",  emoji:"👖", en:"pants",    zh:"裤子",  cat:"clothes", def_en:"Clothing that covers your legs",        def_zh:"遮住腿部的衣物"},
  {id:"shoes",  emoji:"👟", en:"shoes",    zh:"鞋子",  cat:"clothes", def_en:"You wear these on your feet to walk",   def_zh:"穿在脚上走路的东西"},
  {id:"hat",    emoji:"🧢", en:"hat",      zh:"帽子",  cat:"clothes", def_en:"You wear this on top of your head",     def_zh:"戴在头上的东西"},
  {id:"dress",  emoji:"👗", en:"dress",    zh:"裙子",  cat:"clothes", def_en:"A one-piece clothing item for girls",   def_zh:"女孩穿的一件式衣服"},
  {id:"socks",  emoji:"🧦", en:"socks",    zh:"袜子",  cat:"clothes", def_en:"Soft clothing that goes on your feet",  def_zh:"套在脚上的软衣物"},
  {id:"jacket", emoji:"🧥", en:"jacket",   zh:"外套",  cat:"clothes", def_en:"A warm coat you wear outside",          def_zh:"外出时穿的保暖外衣"},
  {id:"gloves", emoji:"🧤", en:"gloves",   zh:"手套",  cat:"clothes", def_en:"Warm coverings you wear on your hands", def_zh:"戴在手上保暖的东西"},
  // Vehicles
  {id:"car",    emoji:"🚗", en:"car",      zh:"汽车",  cat:"vehicles", def_en:"A vehicle with four wheels you drive",   def_zh:"有四个轮子的交通工具"},
  {id:"bus",    emoji:"🚌", en:"bus",      zh:"公共汽车",cat:"vehicles",def_en:"A large vehicle that carries many people",def_zh:"载很多人的大型交通工具"},
  {id:"train",  emoji:"🚂", en:"train",    zh:"火车",  cat:"vehicles", def_en:"A vehicle that travels on rails",         def_zh:"在铁轨上行驶的交通工具"},
  {id:"plane",  emoji:"✈️",en:"plane",    zh:"飞机",  cat:"vehicles", def_en:"A vehicle that flies in the sky",         def_zh:"在天空中飞行的交通工具"},
  {id:"bike",   emoji:"🚲", en:"bike",     zh:"自行车",cat:"vehicles", def_en:"A two-wheeled vehicle you pedal",         def_zh:"用脚踩踏板的两轮交通工具"},
  {id:"boat",   emoji:"⛵", en:"boat",     zh:"船",    cat:"vehicles", def_en:"A vehicle that travels on water",         def_zh:"在水上行驶的交通工具"},
  {id:"rocket", emoji:"🚀", en:"rocket",   zh:"火箭",  cat:"vehicles", def_en:"A vehicle that flies to outer space",     def_zh:"飞向外太空的交通工具"},
  {id:"truck",  emoji:"🚛", en:"truck",    zh:"卡车",  cat:"vehicles", def_en:"A large vehicle for carrying heavy loads", def_zh:"用来运送重物的大型车辆"},
];

module.exports = WORDS_BASE;
